chapter1の演習問題を提出します。
odaira1119/textC- pull request #1
Opened 2023-01-06 07:50 UTC by ohdaira-being

大問3つでQuestion1-1-1、Question1-1-2、Question1-1-3で分けています。

2023-01-16 04:35 UTC, k-miyahara-being requested changes

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +            Product dorayaki = new Product(98, "どら焼き", 210);
Gaia Cloudで採用している[コーディング規約](https://dev-redmine.being.group/projects/sirius-client/wiki/%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84)に一度目を通してみて、これに沿って変数名を書き直してみてください。
特に接頭辞のところをみてみると良いです。
ここ以外の箇所も同様に書き直してみてください。

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +            Console.WriteLine(dorayakiTax);
1度しか使われていない変数はわざわざ宣言せずに直接書いてしまいましょう。

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +            int PrintObjects(MyClass a, MyStruct b) {
Mainメソッド内でしか使えないメソッド（ローカル関数）になっています。
問題の意図に沿っていないと思うので修正をお願いします。

引数名もわかりやすい名前にしてください。

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +            Console.WriteLine("myStruct：({0},{1})", myStruct.X, myStruct.Y);
問題の意図を読み違えています。
PrintObjectメソッドでは、問1の解答は保持したまま、値を2倍するコードを末尾に追加するだけです。

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +                //また、値の代入を行っていないため、同じ結果となった。
問3を解き直して再度結果を確認してみてください。

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +            //4.2で生成したインスタンスをPerson型およびobject型の変数に代入できることを確認してください。
どのように確認しましたか？

2023-01-16 04:35 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +            Console.WriteLine("{0}は、{1}生まれで{2}学年の{3}組です。", student.Name, student.Birthday, student.Grade, student.ClassNumber);
$を使った文字列補完式の方法で書いたほうが見やすいと思うので修正してみてください。

2023-01-16 08:03 UTC, ohdaira-being commented on chapter1/Question1-1-1/Program.cs
> +            Product dorayaki = new Product(98, "どら焼き", 210);
Gaia Cloudのコーディング規約に沿って書き直しました。

2023-01-16 08:03 UTC, ohdaira-being commented on chapter1/Question1-1-1/Program.cs
> +            Console.WriteLine(dorayakiTax);
宣言の行を削除して、直接書くようにしました。

2023-01-16 08:09 UTC, ohdaira-being commented on chapter1/Question1-1-2/Program.cs
> +            int PrintObjects(MyClass a, MyStruct b) {
Main外でメソッドを定義し直しました。

引数をvClassとvStructとしました。

2023-01-16 08:10 UTC, ohdaira-being commented on chapter1/Question1-1-2/Program.cs
> +            Console.WriteLine("myStruct：({0},{1})", myStruct.X, myStruct.Y);
PrintObjectsメソッド内の末尾に値を2倍にするコードを記述しました。

2023-01-16 08:10 UTC, ohdaira-being commented on chapter1/Question1-1-2/Program.cs
> +                //また、値の代入を行っていないため、同じ結果となった。
解き直して、結果と考察ををコメントアウトして記載しました。

2023-01-16 08:12 UTC, ohdaira-being commented on chapter1/Question1-1-3/Program.cs
> +            Console.WriteLine("{0}は、{1}生まれで{2}学年の{3}組です。", student.Name, student.Birthday, student.Grade, student.ClassNumber);
文字列補間式で書き直しました。

2023-01-16 08:13 UTC, ohdaira-being commented on chapter1/Question1-1-3/Program.cs
> +            //4.2で生成したインスタンスをPerson型およびobject型の変数に代入できることを確認してください。
メモを追加しました。

2023-01-16 08:33 UTC, k-miyahara-being requested changes

2023-01-16 08:33 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +
不要なusingは削除しましょう。

2023-01-16 08:33 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +namespace IdiomProduct {
同一ファイルに異なるnamespaceがあるのは違和感があるのでファイルを分けてみましょう。

2023-01-16 08:33 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +            Program.PrintObjects(wMyClass, wMyStruct);
同じクラス内のメソッドなので、Programは省略できます。

2023-01-16 08:33 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +    public class Person {
クラスごとにファイルをわけてみてください。

2023-01-16 08:34 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +            Console.WriteLine("{0}は、{1}生まれで{2}学年の{3}組です。", student.Name, student.Birthday, student.Grade, student.ClassNumber);
OKです。

2023-01-16 08:35 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +                //また、値の代入を行っていないため、同じ結果となった。
OKです。

2023-01-16 08:36 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +            Product dorayaki = new Product(98, "どら焼き", 210);
OKです。

2023-01-16 08:39 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +            Console.WriteLine(dorayakiTax);
OKです。

2023-01-16 08:39 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +            int PrintObjects(MyClass a, MyStruct b) {
OKです。

2023-01-16 08:39 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +            Console.WriteLine("myStruct：({0},{1})", myStruct.X, myStruct.Y);
OKです。

2023-01-16 08:42 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +            //4.2で生成したインスタンスをPerson型およびobject型の変数に代入できることを確認してください。
確認方法が問題の意図に合っていないと思います。
GetAgeメソッドを使用する意図は何でしょうか？

2023-01-16 09:25 UTC, ohdaira-being commented on chapter1/Question1-1-3/Program.cs
> +    public class Person {
クラスごとにファイルを分けました。

2023-01-16 10:00 UTC, ohdaira-being commented on chapter1/Question1-1-3/Program.cs
> +            //4.2で生成したインスタンスをPerson型およびobject型の変数に代入できることを確認してください。
Person型もobject型も使っていませんでした。

やり直しました。
Person型とobject型の変数をそれぞれ生成し、その変数に2で生成した変数を代入して、確認を行いました。

2023-01-16 10:05 UTC, ohdaira-being commented on chapter1/Question1-1-1/Program.cs
> +namespace IdiomProduct {
Productクラスとともに、別ファイルを作成し移動させました。

2023-01-16 10:05 UTC, ohdaira-being commented on chapter1/Question1-1-2/Program.cs
> +            Program.PrintObjects(wMyClass, wMyStruct);
省略しました。

2023-01-16 10:06 UTC, odaira1119 commented on chapter1/Question1-1-1/Program.cs
> +
namespace別でファイルを作成し、作成したファイルの不要なusingを削除しました。

2023-01-17 05:55 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +            //4.2で生成したインスタンスをPerson型およびobject型の変数に代入できることを確認してください。
OKです。

2023-01-17 05:56 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +
OKです。

2023-01-17 05:57 UTC, k-miyahara-being commented on chapter1/Question1-1-1/Program.cs
> +namespace IdiomProduct {
OKです。

2023-01-17 05:58 UTC, k-miyahara-being commented on chapter1/Question1-1-2/Program.cs
> +            Program.PrintObjects(wMyClass, wMyStruct);
OKです。

2023-01-17 05:58 UTC, k-miyahara-being commented on chapter1/Question1-1-3/Program.cs
> +    public class Person {
OKです。

2023-01-17 06:00 UTC, k-miyahara-being approved these changes
レビューOKです。
developにマージしてください。
（Gaia Cloudでは、このあと第三者テストによる動作確認が行われ、問題なければマージとなります。）

2023-01-17 07:03 UTC, merged