10章　章末問題
odaira1119/textC- pull request #10
Opened 2023-02-03 08:14 UTC by ohdaira-being

2023-02-07 09:54 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-2/Program.cs
> +            string wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter10\Sample10-2.txt";
相対パスを使ってください。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-3/Program.cs
> +                "We reorganized the teimetable.",
誤字です。timetable
修正後、出力してもらうと分かりますが4つ目の文も取り出されてしまっています。
正規表現を見直してください。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-3/Program.cs
> +                    foreach (Match MatchedWord in Regex.Matches(wText, wPattern)) {
コーディング規約違反です。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-3/Program.cs
> +                        Console.WriteLine($"開始位置：{MatchedWord.Index,3}");
カンマの後ろは空白を入れてください。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-5/Program.cs
> +                string wPattern = @"<\s*[A-Z]{1,}[>\s]";
閉じタグの場合変換されません。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-5/Program.cs
> +            File.WriteAllLines(wFilePath, wReplacedTexts);
htmlファイルの末尾に下記の行を追加して実行してみてください。
`<HEAD><meta charset="UTF-8"><TITLE>WEBの勉強を開始</TITLE></HEAD>`

実行後のファイルを確認すると末尾に行が追加されるバグが起きています。

2023-02-07 09:54 UTC, k-miyahara-being commented on chapter10/Question10-6/Program.cs
> +            Console.WriteLine(Regex.IsMatch(wExample, wPattern));
問題があいまいだったので少し補足します。

`var wWords = new List<string>() {"しるし", "こもじ", "しんぶんし", "*トマト*", "level", "noon", "k121k", "12321", "<<*<<" };`
上記のリストから、"しんぶんし"、"*トマト*、"level"、"k121k" のみを取り出すようなコードを書いてください。

2023-02-08 06:48 UTC, ohdaira-being commented on chapter10/Question10-2/Program.cs
> +            string wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter10\Sample10-2.txt";
修正しました。

2023-02-08 06:59 UTC, ohdaira-being commented on chapter10/Question10-3/Program.cs
> +                "We reorganized the teimetable.",
誤字を修正し、正規表現が間違っていたことを確認しました。
元々の正規表現`[Tt]ime`の両サイドに`￥ｂ`をつけました。

2023-02-08 07:00 UTC, ohdaira-being commented on chapter10/Question10-3/Program.cs
> +                    foreach (Match MatchedWord in Regex.Matches(wText, wPattern)) {
修正しました。

2023-02-08 07:13 UTC, ohdaira-being commented on chapter10/Question10-5/Program.cs
> +                string wPattern = @"<\s*[A-Z]{1,}[>\s]";
閉じタグにも対応するように修正しました。

2023-02-09 04:58 UTC, ohdaira-being commented on chapter10/Question10-5/Program.cs
> +            File.WriteAllLines(wFilePath, wReplacedTexts);
原因は、大文字のタグを小文字に変更する度にその行を保存していたからでした。
（1行内にある大文字タグの数、行が増えていました。）

小文字への変更方法、変更後の行を保存するタイミング、を変えました。

2023-02-10 06:58 UTC, k-miyahara-being commented on chapter10/Question10-4/Program.cs
>              string wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter10\Sample10-4.txt";
相対パスのままです。

2023-02-10 06:58 UTC, k-miyahara-being commented on chapter10/Question10-2/Program.cs
> +            string wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter10\Sample10-2.txt";
1か所修正されていない箇所があります。

2023-02-10 07:00 UTC, k-miyahara-being commented on chapter10/Question10-2/Program.cs
> +            string wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter10\Sample10-2.txt";
1か所未修正の箇所があります。

2023-02-10 08:03 UTC, ohdaira-being commented on chapter10/Question10-4/Program.cs
>              string wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter10\Sample10-4.txt";
相対パスに修正しました。

2023-02-10 08:12 UTC, k-miyahara-being approved these changes
OKです。

2023-02-10 08:25 UTC, merged