11章　章末問題
odaira1119/textC- pull request #11
Opened 2023-02-06 05:02 UTC by ohdaira-being

2023-02-09 02:31 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-09 02:31 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            XDocument wXdoc = XDocument.Load("../../../../BallSports.xml");//ファイルが見つからないと例外になってしまう
Gaia Cloudではメソッド内にコメントを書く時は、該当のコードの上の行に書くようにしています。
細かいですが合わせてもらうと良いです。

2023-02-09 02:31 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            foreach (XElement wXlist in wXdoc.Root.Elements()) {
変数名が合っていないです。
ファイルから何を取得しているのかが分かるように、より具体的なものであると良いです。
他の箇所も同様に見直してみてください。

2023-02-09 02:31 UTC, k-miyahara-being commented on chapter11/chapter11/Program.cs
> +                    new XElement("teammenbers", "5"),
誤字です。member

2023-02-09 02:31 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            }
要素を1つだけ取得するのに、foreachを使う必要はないですね。

同じ人数のスポーツがあり、それらをすべて取得するつもりなら、Take(1)では先頭しか取れないので意味がありません。

2023-02-09 02:31 UTC, k-miyahara-being commented on chapter11/Question11-2/Program.cs
> +            );
[要望]
SetAttributeValueメソッドを使用したパターンも実装してみてください。

2023-02-10 00:40 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            XDocument wXdoc = XDocument.Load("../../../../BallSports.xml");//ファイルが見つからないと例外になってしまう
承知しました。
コメントの位置をメソッドの上に移動しました。

2023-02-10 00:44 UTC, ohdaira-being commented on chapter11/chapter11/Program.cs
> +                    new XElement("teammenbers", "5"),
修正しました。

2023-02-10 04:14 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            foreach (XElement wXlist in wXdoc.Root.Elements()) {
Listに格納するように全体的に修正をしました。

2023-02-10 04:15 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            }
foreach文内で条件式を使って、表すように修正しました。

2023-02-13 00:52 UTC, ohdaira-being commented on chapter11/Question11-2/Program.cs
> +            );
SetAttributeValueメソッドをを使って、実装しました。

2023-02-13 09:44 UTC, k-miyahara-being requested changes
再度修正をお願いします。

2023-02-13 09:44 UTC, k-miyahara-being commented on chapter11/Question11-1/BallsportList.cs
> +    class BallsportList {
クラスの役割が分かりづらいかもしれません。
プロパティを見ると、1つの球技が持つものになっていますが、
メソッドを見ると、複数の球技が集まったコレクションになっています。
1つの球技を扱うクラスなのか、複数の球技を扱うコレクションクラスなのかをはっきりさせたほうがより良いと思います。

2023-02-13 09:44 UTC, k-miyahara-being commented on chapter11/Question11-1/BallsportList.cs
> +        public static IEnumerable<BallsportList> ReadBallsportLists(string vFilePath) {
メソッド名を見直してみてください。
Listsだとリストが複数あるように感じます。

2023-02-13 09:44 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +                string[] wSoccerData = { "ballsport", "フットボール", "蹴球", "11", "1863" };
配列の要素がすべて独立したものになっていると扱いが難しいと思います。
この配列を利用する際にインデックスを指定していますが、実装者がその数字を覚えておかなければならないのはなかなか厳しいです。
↑のクラスを考え直してから、再度書き直してみてください。

2023-02-15 08:26 UTC, ohdaira-being commented on chapter11/Question11-1/BallsportList.cs
> +    class BallsportList {
BallSportクラスは、一つのBallSport専属にしました。
ファイルの読み込みの際に、複数のBallSportを扱いますが、書き込みと一緒にProgramクラスに書くようにしました。

Good、ありがとうございます！

2023-02-15 08:27 UTC, ohdaira-being commented on chapter11/Question11-1/BallsportList.cs
> +        public static IEnumerable<BallsportList> ReadBallsportLists(string vFilePath) {
ファイルから読み込んだ複数のBallSportを表すので、メソッド名をReadXFileToBallsports()、戻り値をwReadedBallSportsとしました。

2023-02-15 08:32 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +                string[] wSoccerData = { "ballsport", "フットボール", "蹴球", "11", "1863" };
インスタンス生成して、各メソッドを使って追加するようにしました。
①BallSportのインスタンスを生成する
②AddBallSport()メソッドの引数に渡す。
③AddBallSport()メソッド内でBallSport型からXElement型にするToXElement()メソッドの引数に渡す。
④AddBallSport()メソッド内でファイルに追加する。

2023-02-17 07:32 UTC, k-miyahara-being commented on chapter11/Question11-1/BallsportList.cs
> +        public static IEnumerable<BallsportList> ReadBallsportLists(string vFilePath) {
Readedという単語はないです。
メソッド名やコメントから、読み込んだBallSportsが返ってくることがわかるので、シンプルにwBallSportsとかでよいと思います。

2023-02-17 07:39 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +                string[] wSoccerData = { "ballsport", "フットボール", "蹴球", "11", "1863" };
やはり、BallSportCollectionクラスは冗長な気がしますね。
wBallSportCollection.BallSports はそのままwBallSportsに置き換えられますので。

2023-02-17 07:50 UTC, k-miyahara-being requested changes
細かい修正をお願いします。

2023-02-17 07:50 UTC, k-miyahara-being commented on chapter11/NewSample11-3.xml
> +</difficultkanji>
不要なファイルでしたら削除しておいてください。

2023-02-17 07:50 UTC, k-miyahara-being commented on chapter11/Question11-1/BallSport.cs
> +        // BallSportのインスタンスを受け取り、XElement型を返すメソッド
不要なコメントなので削除してください。
他の箇所も同様です。

2023-02-17 07:50 UTC, k-miyahara-being commented on chapter11/Question11-1/BallSport.cs
> +                       new XElement("firstplayed", vBallSport.Firstplayed)
インデントがずれています。

2023-02-17 07:50 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            XDocument wXdoc = XDocument.Load(vFilePath);
メソッド内の先頭行は空行にする必要はありません。
他の箇所も同様です。

2023-02-17 07:50 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            };
`{`の前の空白が抜けています。
インデントがずれています。

2023-02-17 07:50 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +
すべての行に対してコメントを書く必要がありません。

第三者目線で、ぱっと見なにをしているかわかりづらそうな箇所で、処理のかたまりに対して書くことが多いです。
if文とかが多いですかね。

2023-02-20 00:31 UTC, ohdaira-being commented on chapter11/Question11-1/BallsportList.cs
> +        public static IEnumerable<BallsportList> ReadBallsportLists(string vFilePath) {
シンプルにwBallSportsにしました。

2023-02-20 00:32 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +                string[] wSoccerData = { "ballsport", "フットボール", "蹴球", "11", "1863" };
BallSportCollectionクラスは、冗長でした。
削除してます。

2023-02-20 00:35 UTC, ohdaira-being commented on chapter11/NewSample11-3.xml
> +</difficultkanji>
削除しました。

2023-02-20 00:35 UTC, ohdaira-being commented on chapter11/Question11-1/BallSport.cs
> +        // BallSportのインスタンスを受け取り、XElement型を返すメソッド
不要なコメントを削除しました。

2023-02-20 00:36 UTC, ohdaira-being commented on chapter11/Question11-1/BallSport.cs
> +                       new XElement("firstplayed", vBallSport.Firstplayed)
インデントを揃えました。

2023-02-20 00:37 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            XDocument wXdoc = XDocument.Load(vFilePath);
不要な空行を削除しました。

2023-02-20 00:37 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            };
空白とインデントを揃えました。

2023-02-20 00:37 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +
不要だと判断したコメントを削除しました。

2023-02-20 04:30 UTC, ko-kato-being commented on chapter11/Question11-1/Program.cs
> +            }
ここのコードは改良の余地があります。
パフォーマンスを意識してみると良いです。
パフォーマンスとは計算量(オーダー)のことです。
このあたり知らなければ調べてみてください。

改めてコードの話ですが、いまは O(N^2) となっています。
for ループの中で毎回 Max() を使用しているのが微妙なかんじですね。
例えばですが、↓のようなコードであれば O(2N) で済みます。

```
int wMaxCount = wBallsports.Max(x => x.Teammembers);
foreach (var wBallSport in wBallsports) {
    if (!(wBallSport.Teammembers == wMaxCount)) continue;
    Console.WriteLine(wBallSport.Name);
}
```
他にも方法はいろいろあると思います。
時間がある時で良いので、どうすれば計算量を減らせるか考えてみてください。


余談ですが、Teammembers はちょっとわかりにくい名前かもですね。
変数名から型が推測しにくい場合は微妙なネーミングになってないか疑ってみると良いです。
TeamSizeとか MemberCount とかの方がわかりやすいかも？

2023-02-21 04:56 UTC, k-miyahara-being commented on chapter11/Question11-1/BallsportList.cs
> +        public static IEnumerable<BallsportList> ReadBallsportLists(string vFilePath) {
修正が反映されていないようです。
もう一度確認をお願いします。

2023-02-21 05:10 UTC, k-miyahara-being requested changes
再度修正をお願いします。

2023-02-21 05:10 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +        public static IEnumerable<BallSport> ReadXFileToBallsports(string vFilePath) {
クラス内でしか使わないメソッドはprivateにしておきましょう。

2023-02-21 05:10 UTC, k-miyahara-being commented on chapter11/Question11-1/BallSport.cs
> +        public static XElement ToXElement(BallSport vBallSport) {
メソッドを見直してみてください。
staticでないメソッドにできます。
このメソッドの呼び出し元も見てみると良いです。

2023-02-21 05:10 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            IEnumerable<BallSport> wBallsports = ReadXFileToBallsports(wFilePath);
変数名がパスカルケースになっていません。
他の箇所にも同じようなものがないかチェックしてみてください。

2023-02-21 05:10 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +                AddBallSport(wSoccer, wFilePath);
変数宣言は不要です。

2023-02-21 05:28 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            }
計算量を考慮して、修正しました。
if文をなくして、foreach文中では最大チームメンバーの競技だけをループするようにしました。

MemberCountにしました。

2023-02-21 05:33 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +        public static IEnumerable<BallSport> ReadXFileToBallsports(string vFilePath) {
privateにしました。

2023-02-21 05:38 UTC, ko-kato-being commented on chapter11/Question11-1/Program.cs
> +            }
修正ありがとうございました。
良いかんじです！

2023-02-21 05:44 UTC, ohdaira-being commented on chapter11/Question11-1/BallSport.cs
> +        public static XElement ToXElement(BallSport vBallSport) {
動的メソッドに書き直しました。

2023-02-21 05:48 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            IEnumerable<BallSport> wBallsports = ReadXFileToBallsports(wFilePath);
パスカルケースに修正しました。

2023-02-21 06:27 UTC, k-miyahara-being requested changes

2023-02-21 06:27 UTC, k-miyahara-being commented on chapter11/Question11-1/Program.cs
> +            XElement wAddData = new XElement(vBallSportData.ToXElement());
ToXElement()で帰ってくるインスタンスを引数にさらにnewする必要はありますか？

2023-02-21 06:27 UTC, k-miyahara-being commented on chapter11/Question11-1/BallSport.cs
> +        public static XElement ToXElement(BallSport vBallSport) {
メソッドを簡略化できます。

2023-02-21 06:27 UTC, k-miyahara-being commented on chapter11/Question11-1/BallSport.cs
> +        public static XElement ToXElement(BallSport vBallSport) {
メソッドを簡略化できます。

2023-02-21 06:33 UTC, ohdaira-being commented on chapter11/Question11-1/BallSport.cs
> +        public static XElement ToXElement(BallSport vBallSport) {
簡略化しました。

2023-02-21 06:35 UTC, ohdaira-being commented on chapter11/Question11-1/Program.cs
> +            XElement wAddData = new XElement(vBallSportData.ToXElement());
ないです。
不要なインスタンス生成を削除しました。

2023-02-21 06:43 UTC, k-miyahara-being approved these changes
OKです。

2023-02-21 06:56 UTC, merged