12章　章末問題
odaira1119/textC- pull request #12
Opened 2023-02-16 05:08 UTC by ohdaira-being

2023-02-17 08:17 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-1/Employee.cs
> +        public string Name { get; set; }
コメントの意味がありません。
プロパティが表しているものを日本語で記述するとよいです。
クラスのコメントも同様です。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-1/Program.cs
> +
不要な空行です。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-1/Program.cs
> +                IndentChars = " ",
インデントを空白1つ分にしているのは理由がありますか？
既定値は2つ分です。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-1/Program.cs
> +            var wEmployeeCollection = new EmployeeCollection(wEmployee);
第三者でもコードから簡単に読み取れるのでコメントは不要です。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-2/NovelistCollection.cs
> +        //[XmlArrayItem("novelists", typeof(Novelist))]
不要なコメントは削除してください。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-2/Program.cs
> +                new Novelist("アーサー・C・クラーク",new DateTime(1917,12,16),wMasterpieces)
カンマの後に空白を入れてください。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-2/Program.cs
> +            // 問題2-2 XMLファイルのファイルパス
コメントが間違っています。

2023-02-17 08:17 UTC, k-miyahara-being commented on chapter12/Question12-2/Program.cs
> +using System.Linq;
不要なusingは削除してください。

2023-02-17 08:48 UTC, ko-kato-being commented on chapter12/Question12-1/Program.cs
> +                foreach (Employee wLoadedEmployee in (wSerializer.Deserialize(wReader) as EmployeeCollection).Employees) {
`(wSerializer.Deserialize(wReader) as EmployeeCollection).Employees`
このコードはアンチパターンになります。
as はキャストに失敗した場合に null を返すため、必ず null チェックが必要になります。
いまのコードだとキャストに失敗した場合に NullReferenceException が発生します。
そもそもキャストに失敗しない想定ならば、() を使ってキャストするのが良いです。

あとついでにですが、`wLoadedEmployee` はちょっと冗長な名前に感じました。
Loaded という単語がついていてはたして嬉しいことがあるのか？と考えてみると良いです。
変数名を考える時のコツですが、その変数のスコープを意識すると良いです。
スコープが大きくて様々なところで参照されるものであれば、なるべく具体的な変数名にするのが良いです。
逆に、スコープが小さくて付近のコードを見ればどのような使われ方をするかわかるものであれば、かなり簡素な名前でも問題ないです。

2023-02-20 02:12 UTC, ohdaira-being commented on chapter12/Question12-1/Employee.cs
> +        public string Name { get; set; }
日本語で記述しました。

2023-02-20 02:12 UTC, ohdaira-being commented on chapter12/Question12-1/Program.cs
> +
削除しました。

2023-02-20 02:13 UTC, ohdaira-being commented on chapter12/Question12-1/Program.cs
> +            var wEmployeeCollection = new EmployeeCollection(wEmployee);
削除しました。

2023-02-20 02:18 UTC, ohdaira-being commented on chapter12/Question12-2/Program.cs
> +                new Novelist("アーサー・C・クラーク",new DateTime(1917,12,16),wMasterpieces)
空白を追加しました。

2023-02-20 02:19 UTC, ohdaira-being commented on chapter12/Question12-2/Program.cs
> +            // 問題2-2 XMLファイルのファイルパス
Jsonファイルでした。

2023-02-20 02:19 UTC, ohdaira-being commented on chapter12/Question12-2/Program.cs
> +using System.Linq;
削除しました。

2023-02-20 02:56 UTC, ohdaira-being commented on chapter12/Question12-1/Program.cs
> +                foreach (Employee wLoadedEmployee in (wSerializer.Deserialize(wReader) as EmployeeCollection).Employees) {
EmployeeCollectionクラスは、Employeeクラスのコレクションクラスなので、キャストに失敗しないと想定し、キャスト演算子()を使うように修正しました。

foreach文のwLoadEmployeeは、wEmployeeとしました。

2023-02-20 04:07 UTC, ko-kato-being commented on chapter12/Question12-1/Program.cs
> +                foreach (Employee wLoadedEmployee in (wSerializer.Deserialize(wReader) as EmployeeCollection).Employees) {
修正ありがとうございました。
良いかんじです！

2023-02-21 06:39 UTC, k-miyahara-being commented on chapter12/Question12-1/Program.cs
> +                IndentChars = " ",
既定値が2つなので、2つに設定する場合は初期化子で設定する必要はないです。

2023-02-21 06:54 UTC, ohdaira-being commented on chapter12/Question12-1/Program.cs
> +                IndentChars = " ",
Indentをtrueにするとデフォルトが空白二つ分なんですね。
IndentChars を設定しないように、修正しました。

2023-02-21 07:03 UTC, k-miyahara-being approved these changes
OKです。

2023-02-21 07:11 UTC, merged