13章　章末問題
odaira1119/textC- pull request #13
Opened 2023-02-20 09:11 UTC by ohdaira-being

以下ファイルにコーディングしました。
・Author.cs
・Book.cs
・BooksDbContext.cs
・Configuration.cs
・Program.cs

2023-03-06 05:56 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Author.cs
> +        public int Id { get; set; }
IDは後から書き換わると問題なので、読み取り専用のほうが良いです。
書籍IDも同様です。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Book.cs
> +        [MaxLength(16)]
文字数を制限しているのは理由がありますか？
名前に関しては制限を超えてくる可能性が大いにある（英語など）ので、制限をつけないのが無難かと思います。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Models/BooksDbContext.cs
> +            : base("name=BooksDbContext") {
ここは無理に改行しなくてもよいです。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Models/BooksDbContext.cs
> +                );
ここも、改行がないほうが見やすいです。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +        private static void InitializBooks() {
Initializeの綴りが間違っています。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +            DisplayAllAuthors();
コンソール出力が見づらいので、どこからどこまでがどの問題の解答であるか、わかるようにしておいてもらえると嬉しいです！

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +
余分な空行があります。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +            AddBooks(new Book("銀河鉄道の夜", 1989, wKenjiMiyazawa));
AddBooksのたびに、著者が別人として追加されていっています。
著者テーブルに同じ人がすでにいる場合は、追加されないようにしてください。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                        $"ID：{wBook.Id} タイトル：{wBook.Title}発行年：{wBook.PublishedYear} " +
見やすくするために、タイトルと発行年の間にも空白を入れてください。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +
毎度DBへの接続を行っているとコストがかかるので、wDbを使いまわすようにすると良いです。

2023-03-06 05:56 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Book.cs
> +        }
オーバーロードではなく1つにまとめて書いてみてください。

2023-03-06 08:29 UTC, ohdaira-being commented on chapter13/chapter13/Models/BooksDbContext.cs
> +            : base("name=BooksDbContext") {
不要な改行をなくしました。

2023-03-06 08:30 UTC, ohdaira-being commented on chapter13/chapter13/Models/BooksDbContext.cs
> +                );
同じく開業をなくしました。

2023-03-06 08:30 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +        private static void InitializBooks() {
eが抜けていたので、追加しました。

2023-03-06 08:37 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +            DisplayAllAuthors();
適所に改行と問題番号を出力するようにしました！

2023-03-06 08:38 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +
不要な空行をなくしました。

2023-03-07 02:21 UTC, ohdaira-being commented on chapter13/chapter13/Models/Author.cs
> +        public int Id { get; set; }
setterを削除し、完全に読み取り専用にしました。

2023-03-07 02:24 UTC, ohdaira-being commented on chapter13/chapter13/Models/Book.cs
> +        [MaxLength(16)]
テキストで学んだことを使ってみたかったです。
目的なく制限するのは、よくなかったです。
削除しました。

2023-03-07 03:22 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +            AddBooks(new Book("銀河鉄道の夜", 1989, wKenjiMiyazawa));
AddBooksメソッド内の条件式が間違えていましたので、修正しました。
Allメソッドで記述していたところをAnyメソッドに書き換えています。

2023-03-07 03:23 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                        $"ID：{wBook.Id} タイトル：{wBook.Title}発行年：{wBook.PublishedYear} " +
空白を追加しています。

2023-03-07 04:53 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +
usingをまとめ、wDbを一つにしました。

2023-03-07 05:09 UTC, ohdaira-being commented on chapter13/chapter13/Models/Book.cs
> +        }
コンストラクタの引数を4つにして、一つにまとめました。

2023-03-07 08:24 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Author.cs
> +        public int Id { get; set; }
クラス内で書き換え可能にしたのには理由がありますか？

2023-03-07 08:27 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +        private static void InitializBooks() {
InitializAuthorsのほうも修正をお願いします。

2023-03-07 08:29 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +
他にもあるので確認をお願いします。

2023-03-07 08:35 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +
AddBooksメソッドやAddAuthorメソッドも見直してみてください。
書籍を1冊追加するごとに接続しているので、かなりコストがかかっています。

2023-03-07 08:41 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Book.cs
> +        }
vPublisherのコメントが間違っているので修正をお願いします。
著者名→発行者(出版社?)名

2023-03-09 07:10 UTC, odaira1119 commented on chapter13/chapter13/Models/Author.cs
> +        public int Id { get; set; }
setterを削除して、完全に読み取り専用プロパティにするとIDがふられないようになったためです。
IDはEntity Frameworkにより付与されることが関係していると思いますが、原因をあまりわかっていません。

2023-03-09 07:11 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +        private static void InitializBooks() {
修正しました。

2023-03-09 07:13 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +
確認して、削除しました。

2023-03-09 07:16 UTC, ohdaira-being commented on chapter13/chapter13/Models/Book.cs
> +        }
修正しました。

2023-03-10 02:51 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +
一冊ごとに処理するようにしていたので、コストがかかっていました。
Book、Author、それぞれにListを準備して、Listから追加するようにしました。

また、実行すると毎回初期化していたところもコストがかかっていると思い、修正しました。
毎回初期化していた理由は、DBにどんなデータが入っていても追加してしまう実装だったからです。
そのため、追加する際にDBに同じデータが入っていないか、チェックしてから追加を行うようにしました。

2023-03-13 04:17 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                foreach (Book wBook in wDb.Books) {
`wDb.Books`は複数箇所で使われている、かつ途中で書き換わらないので、変数において使いまわすと良いです。

2023-03-13 04:18 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +            using (var wDb = new BooksDbContext()) {
不要になったメソッドは削除してください。

2023-03-13 04:21 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Book.cs
> +        }
修正されていません。
著者名 or 出版社 どちらが正しいですか？

2023-03-14 02:10 UTC, ohdaira-being commented on chapter13/chapter13/Models/Book.cs
> +        }
著者名が正しいです。
プロパティ名・変数名が不適切なので、変更しました。

2023-03-14 02:17 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                foreach (Book wBook in wDb.Books) {
wDb.Booksを変数wDbBooksにおいて使いまわすようにしました。

2023-03-14 02:19 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +            using (var wDb = new BooksDbContext()) {
使っていないメソッドをすべて削除しました。
（削除用のDeleteメソッドと一つ一つ追加するAddメソッドを削除しました。）

2023-03-14 02:46 UTC, k-miyahara-being commented on chapter13/chapter13/Models/Book.cs
> +        }
AuthorNameプロパティは必要ですか？
Authorプロパティが著者名情報を持つので、Author != nullかつAuthorName = null という状況は矛盾しています。
著者追加時に著者名しかわかっていなら、Name以外をnullにしてnewすればよいです。

2023-03-14 08:55 UTC, ohdaira-being commented on chapter13/chapter13/Models/Book.cs
> +        }
BookをBook（タイトル, 発行年, Author）ではなく、Book（タイトル, 発行年, 著者名）の形でDBに追加できたら楽そうだと思っていたので、AuthorNameプロパティを準備していました。

理想的な動作としては、
①後者の形でAdd
②DBのAuthor.Nameを検索
③著者名と同じAuthor.Nameが
　・ある場合は、著者名(string型)をDBのAuthorに置き換える
　・ない場合は、著者名(string型)のまま
④Bookに追加
です。

しかし、こうした場合、Book（タイトル, 発行年, 著者名）の形でDBに追加した後にBook（タイトル, 発行年, Author）の形で追加しても最初に追加したBook（タイトル, 発行年, 著者名）の著者名は置き換わらないことやそもそもAuthorを先に定義しておけばいい話だったので、不必要な機能でした。

プロパティがもつ情報が重複するのはおかしいので、AuthorNameを削除しました。

2023-03-15 01:20 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                    $"著者名：{ wBook.Author.Name } " +
ここでnull参照例外が発生するので、対応をお願いします。
他の箇所でも同様に例外が発生するので、確認をお願いします。

2023-03-15 07:41 UTC, odaira1119 commented on chapter13/chapter13/Program.cs
> +                    $"著者名：{ wBook.Author.Name } " +
例外が発生する原因は、修正前のコードを実行した際、DBにAuthor=nullのBookをAddしているからだと思います。
修正後では、BookのAuthorプロパティがnullになることを想定していませんでした。
Author=nullのBookをAddできますが、そうした場合以下2つの例外が発生する状態でした。
①Authorプロパティを呼び出した際、Authorがnullによるnull参照例外が発生する
②BooKクラス・Authorクラスのプロパティに[Required]を付与しているため、そのプロパティがnullだとDBをSaveChangesする際にDbEntityValidationException例外が発生する。
①②ともに、特定のプロパティがnullになると起こります。

そのため以下、2点修正しました。
①修正前のDBを削除する必要があるので、DBを初期化するInitializeDBメソッドを実装しました。
②BookだとTitleとAuthor、AuthorだとNameがnullだとArgumentException例外をスローするようにして、例外処理を実装しました。

2023-03-15 09:11 UTC, k-miyahara-being requested changes

2023-03-15 09:11 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                Console.WriteLine("例外をキャッチしました。（Bookは、TitleとAuthorが必要です。）");
コンソールに出力する内容は、ユーザー向けの表現にしてください。

2023-03-15 09:11 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +            Author wKenjiMiyazawa = new Author("宮沢賢治", new DateTime(1896, 8, 27), "男性");
間違いではありませんが、右辺から型がわかるので、varで良いです。
newのときはvarくらいで覚えてしまっても良いかなと思います。

2023-03-15 09:11 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +            }
`}` の右に不要な空白があるので削除してください。

Visual Studioで、空白を表示する機能があります。もし表示OFFなら、ONにしておくと良いと思いますよ。
今回のような不要な空白や、インデントのずれなどに気づきやすくなります。（ON/OFF の切り替えは、Ctrl + E + S でできます。）
SourceTreeの差分でも空白が表示されているので、そこで確認するのもアリです。

また、不要な空白やインデントなどはコード整形を使えば自動で直してくれます。

2023-03-15 09:11 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                    $"著者名：{ wBook.Author.Name } " +
`{ wBook.Author.Name }` 内の前後の空白は不要です。
他の箇所にもあるので、コード整形を使ってみると良いです。

2023-03-15 09:44 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +            }
空白の表示設定をしていなかったので、設定しました。
ありがとうございます。
空白は、削除しています。

2023-03-15 09:47 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +            Author wKenjiMiyazawa = new Author("宮沢賢治", new DateTime(1896, 8, 27), "男性");
newの時は、暗示的な表示にするように修正しました。

2023-03-15 09:50 UTC, odaira1119 commented on chapter13/chapter13/Program.cs
> +                    $"著者名：{ wBook.Author.Name } " +
前後の空白を削除しました。
コード整形では、空白を整形してくれなかったです。

2023-03-15 09:53 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                Console.WriteLine("例外をキャッチしました。（Bookは、TitleとAuthorが必要です。）");
日本語で何が必要なのかを書くように修正しました。

2023-03-16 01:13 UTC, k-miyahara-being reviewed
修正をお願いします。

2023-03-16 01:13 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                    wDb.Books.AddRange(wAddBooksList).Distinct();
一度ローカルのリストに入れてから別のリストにそっくりそのまま入れるのは無駄な処理だと思います。

2023-03-16 01:13 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                        if (wDb.Books.Any(x => x.Title == wBook.Title)) continue;
書籍名が同じだが、著者や発行年は違う、というものが追加できないようになっています。

2023-03-16 01:16 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +            if (vDb.Authors.Any(x => x.Name == wAuthorName)) vBook.Author = vDb.Authors.Single(x => x.Name == wAuthorName);
同姓同名の著者が追加できないようになっています。
同姓同名、同じ誕生日、同じ性別なら同一人物としてよいです。

2023-03-16 04:47 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                    wDb.Books.AddRange(wAddBooksList).Distinct();
わざわざListに格納するのをやめて、一つ一つ追加するように修正しました。

2023-03-16 04:50 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                        if (wDb.Books.Any(x => x.Title == wBook.Title)) continue;
タイトルだけでなく、完全一致したときのみ追加しないように修正しました。

2023-03-16 04:51 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +            if (vDb.Authors.Any(x => x.Name == wAuthorName)) vBook.Author = vDb.Authors.Single(x => x.Name == wAuthorName);
名前だけでなく、完全一致したときのみ著者情報を書き換えるようにしました。

2023-03-16 07:15 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                        if (wDb.Books.Any(x => x.Title == wBook.Title)) continue;
書籍名、発行年、著者が同じ書籍が同一とみなされず、追加できてしまっています。
テストデータ `new Book("ワンピース", 2000, wSosekiNatsume),` を、2つ書いてみて実行してみてください。

2023-03-16 07:18 UTC, k-miyahara-being commented on chapter13/chapter13/Program.cs
> +                    wDb.SaveChanges();
https://github.com/ohdaira-being/textC-/pull/13#discussion_r1138214667 と同様に、同姓同名、同じ誕生日、同じ性別の著者が同一人物とみなされず、追加できてしまっています。

2023-03-16 07:35 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                        if (wDb.Books.Any(x => x.Title == wBook.Title)) continue;
同時に同じBookを追加したとき場合を考えられていませんでした。
SaveChangesのタイミングをBookをAddしたタイミングに合わせました。

2023-03-16 07:36 UTC, ohdaira-being commented on chapter13/chapter13/Program.cs
> +                    wDb.SaveChanges();
同様に修正しました。

2023-03-16 07:39 UTC, k-miyahara-being approved these changes

2023-03-16 07:57 UTC, merged