14章　章末問題
odaira1119/textC- pull request #14
Opened 2023-02-24 06:59 UTC by ohdaira-being

2023-02-24 07:03 UTC, ohdaira-being commented
コミットコメントに編集ファイルを記載するのを忘れていました。
すいません。
ここに編集ファイルを記載させていただきます。

・Question14-1
・Question14-1
・Question14-1
・Question14-1

2023-03-06 08:03 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-1/Program.cs
> +            }
問題の要件を満たせていません。
パラメータを与えるようにしてください。
テキストファイルで、EXEファイルのパスとセットでパラメータを書くようにすると良いです。
例：`%SystemRoot%\system32\notepad.exe あああ`

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-2/Program.cs
> +            var wAssemblyVersion = wAssembly.GetName().Version;
明示的な型を使ってください。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-2/Program.cs
> +                );
VersionクラスではToString()をオーバーライドしているので、単純にVersionのオブジェクトを参照するだけでバージョンを表す文字列になります。
`Console.WriteLine(wAssemblyVersion);`

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-2/Program.cs
> +                );
FileVersionInfoクラスのFileVersionプロパティを使用することでより簡単に文字列を取得できます。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-3/CalendarOption.cs
> +            get { return (string)this["StringFormat"]; }
簡略化できます。
他の箇所も同様です。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-4/Program.cs
> +            }
htmlファイルとして保存するように書いてみてください。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-5/Program.cs
> +                IEnumerable<ZipArchiveEntry> wTxtFiles = wZipFile.Entries.Where(x => wRegex.IsMatch(x.Name));
Pathクラスを使って拡張子を取得すれば、正規表現でのチェックは不要です。
書き直してみてください。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-5/Program.cs
> +                    if (wTxtFile != null) {
wTxtFilesの中身が空の場合は、foreach文の中に入りません。
wTextFileはnullになることがないのでnullチェックは不要になります。

2023-03-06 08:03 UTC, k-miyahara-being commented on chapter14/Question14-6/Program.cs
> +                );
より便利なConvertTimeBySystemTimeZoneIdメソッドというものがあります。

2023-03-07 05:28 UTC, ohdaira-being commented on chapter14/Question14-2/Program.cs
> +            var wAssemblyVersion = wAssembly.GetName().Version;
明示的な型で宣言するように修正しました。

2023-03-07 05:32 UTC, ohdaira-being commented on chapter14/Question14-2/Program.cs
> +                );
VersionクラスのToStringメソッドを使って、表すようにしました。

2023-03-07 05:34 UTC, ohdaira-being commented on chapter14/Question14-2/Program.cs
> +                );
FileVersionプロパティを参照して、表すように修正しました。

2023-03-07 05:35 UTC, ohdaira-being commented on chapter14/Question14-3/CalendarOption.cs
> +            get { return (string)this["StringFormat"]; }
式本体で簡略化しました。

2023-03-07 05:37 UTC, ohdaira-being commented on chapter14/Question14-4/Program.cs
> +            }
保存先のファイルの拡張子を.htmlに変更しました。

2023-03-07 05:41 UTC, ohdaira-being commented on chapter14/Question14-5/Program.cs
> +                    if (wTxtFile != null) {
if文を削除しました。

2023-03-07 05:55 UTC, ohdaira-being commented on chapter14/Question14-5/Program.cs
> +                IEnumerable<ZipArchiveEntry> wTxtFiles = wZipFile.Entries.Where(x => wRegex.IsMatch(x.Name));
PathクラスのGetExtensionメソッド使って、書き直しました。

2023-03-07 06:02 UTC, ohdaira-being commented on chapter14/Question14-6/Program.cs
> +                );
ConvertTimeBySystemTimeZoneIdメソッドを使って、書き直しました。

2023-03-07 07:28 UTC, ohdaira-being commented on chapter14/Question14-1/Program.cs
> +            }
パラメータを渡していなかったので、修正しました。
テキストファイルを読み込んで、コンソールアプリを複数実行するアプリにしました。

2023-03-07 09:03 UTC, k-miyahara-being requested changes

2023-03-07 09:03 UTC, k-miyahara-being commented on chapter14/Question14-1/Program.cs
> +            var wFilePath = @"..\..\..\Sample14-1.txt";
明示的な型を使ってください。

2023-03-07 09:03 UTC, k-miyahara-being commented on chapter14/Question14-4/Program.cs
> +            wWebClient.Encoding = Encoding.UTF8;
初めからセットしておく予定の値なら、初期化子で定義しておきましょう。

2023-03-07 09:03 UTC, k-miyahara-being commented on chapter14/Question14-6/Program.cs
> +                );
WriteLineの改行は不要です。

2023-03-07 09:04 UTC, k-miyahara-being commented on chapter14/Question14-2/Program.cs
> +            var wAssemblyVersion = wAssembly.GetName().Version;
ほかにもあるので修正してください。
また、そもそも変数宣言が必要か検討してください。

2023-03-10 03:01 UTC, ohdaira-being commented on chapter14/Question14-2/Program.cs
> +            var wAssemblyVersion = wAssembly.GetName().Version;
そもそも変数宣言が不要でした。

2023-03-10 03:02 UTC, ohdaira-being commented on chapter14/Question14-6/Program.cs
> +                );
改行をなくしました。

2023-03-10 03:03 UTC, ohdaira-being commented on chapter14/Question14-1/Program.cs
> +            var wFilePath = @"..\..\..\Sample14-1.txt";
明示的にしました。

2023-03-10 03:59 UTC, ohdaira-being commented on chapter14/Question14-4/Program.cs
> +            wWebClient.Encoding = Encoding.UTF8;
初期化子で定義しました。

2023-03-13 04:28 UTC, k-miyahara-being approved these changes

2023-03-14 02:22 UTC, merged