15章　章末問題
odaira1119/textC- pull request #15
Opened 2023-02-27 02:50 UTC by ohdaira-being

編集ファイル
・Book.cs
・Category.cs
・Library.cs
・Program.cs

2023-03-06 09:25 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Library.cs
> +
不要な空行です。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Category.cs
> +            return $"Id：{Id}、カテゴリ名：{Name}";
コーディング規約に則って、thisをつけるようにしておきましょう。
また、簡略化できます。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Book.cs
> +        public int PublisherYear { get; set; }
PublishedYearのほうが適切かと思います。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Book.cs
> +            return $"発行年：{PublisherYear}、カテゴリ名：{CategoryId}、価格：{Price}、タイトル：{Title}";
Categoryクラスの指摘と同様です。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Program.cs
> +            foreach (var wBook in Library.Books.OrderByDescending(x => x.PublisherYear).ThenByDescending(x => x.Price)) {
明示的な型を使用してください。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Program.cs
> +            }
何年が何冊なのか分かるような出力にすると分かりやすいです。
あと、どこからどこまでがどの問題の解答かわかるような出力にしてもらえると助かります。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Program.cs
> +            }
同じ名前のカテゴリが出力されないようにしてください。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Program.cs
> +            }
おそらくデータの間違いですが、ServerとWindowsに同じ名前の書籍があります。

2023-03-06 09:25 UTC, k-miyahara-being commented on chapter15/Question15-1/Program.cs
> +            foreach (var wBook in wBookGroups.Where(x => x.Count >= 4)) {
明示的な型を使ってください。

2023-03-07 07:36 UTC, ohdaira-being commented on chapter15/Question15-1/Library.cs
> +
削除しました。

2023-03-07 07:37 UTC, ohdaira-being commented on chapter15/Question15-1/Category.cs
> +            return $"Id：{Id}、カテゴリ名：{Name}";
thisを追加しました。

2023-03-07 07:38 UTC, ohdaira-being commented on chapter15/Question15-1/Book.cs
> +        public int PublisherYear { get; set; }
過去形にすべきでした。
修正しました。

2023-03-07 07:39 UTC, ohdaira-being commented on chapter15/Question15-1/Book.cs
> +            return $"発行年：{PublisherYear}、カテゴリ名：{CategoryId}、価格：{Price}、タイトル：{Title}";
thisを追加しました。

2023-03-07 07:39 UTC, ohdaira-being commented on chapter15/Question15-1/Program.cs
> +            foreach (var wBook in Library.Books.OrderByDescending(x => x.PublisherYear).ThenByDescending(x => x.Price)) {
明示的な型で宣言しました。

2023-03-07 07:44 UTC, ohdaira-being commented on chapter15/Question15-1/Program.cs
> +            }
発行年と発行書籍数をセットで出力するようにしました。
また、問題ごとに問題番号を出力するようにしました。

2023-03-07 07:49 UTC, ohdaira-being commented on chapter15/Question15-1/Program.cs
> +            }
GroupByメソッドで重複をまとめました。

2023-03-07 07:52 UTC, ohdaira-being commented on chapter15/Question15-1/Program.cs
> +            }
データの間違いでした。
修正しました。

2023-03-07 08:00 UTC, ohdaira-being commented on chapter15/Question15-1/Program.cs
> +            foreach (var wBook in wBookGroups.Where(x => x.Count >= 4)) {
明示的な型を使いました。

2023-03-07 09:09 UTC, k-miyahara-being commented on chapter15/Question15-1/Category.cs
> +            return $"Id：{Id}、カテゴリ名：{Name}";
簡略化されていません。

2023-03-07 09:09 UTC, k-miyahara-being commented on chapter15/Question15-1/Book.cs
> +            return $"発行年：{PublisherYear}、カテゴリ名：{CategoryId}、価格：{Price}、タイトル：{Title}";
簡略化されていません。

2023-03-07 09:11 UTC, k-miyahara-being commented on chapter15/Question15-1/Program.cs
> +            foreach (var wBook in Library.Books.OrderByDescending(x => x.PublisherYear).ThenByDescending(x => x.Price)) {
他にもあります。
同じ指摘がされないように、該当箇所を修正したときに全体も併せて見直すようにすると良いです。

2023-03-10 05:46 UTC, ohdaira-being commented on chapter15/Question15-1/Program.cs
> +            foreach (var wBook in Library.Books.OrderByDescending(x => x.PublisherYear).ThenByDescending(x => x.Price)) {
foreach文内の変数は、明示的にしました。
LinqのJoinメソッドやGroupJoinメソッドを使って、再定義している変数は、匿名型を使っていてvarのままです。
明示的にしようとしましたが、できませんでした。

2023-03-10 05:46 UTC, ohdaira-being commented on chapter15/Question15-1/Category.cs
> +            return $"Id：{Id}、カテゴリ名：{Name}";
式本体を使って簡略化しました。

2023-03-10 05:47 UTC, ohdaira-being commented on chapter15/Question15-1/Book.cs
> +            return $"発行年：{PublisherYear}、カテゴリ名：{CategoryId}、価格：{Price}、タイトル：{Title}";
式本体を使って、簡略化しました。

2023-03-14 02:25 UTC, merged