16章　章末問題
odaira1119/textC- pull request #16
Opened 2023-03-06 03:48 UTC by ohdaira-being

【問題16-1】
　編集したファイル（WPFアプリ）
・IInitializeWithWindow.cs
・MainWindow.xaml.cs
　確認方法
①「ファイル選択」ボタンを押下するとファイルピッカーが出力します。
問題文に沿って、ファイルピッカーは、.txtファイルのみ選択できるようにしています。
②txtファイルを選択して、画面にファイルの内容が出力されれば、確認完了です。

【問題16-2】
　編集したファイル（WindowsFormアプリ）
・From1.cs
　確認方法
①（ディレクトリ選択）ボタンを押下するとディレクトリを選択するダイアログが出力します。
②ディレクトリを選択して、「OK」ボタンを押下すると「検索するディレクトリ」の下に選択したディレクトリのフルパスが出力します。 ③「検索」ボタンを押下すると、検索が始まります。
④検索が完了すると「検索結果」の下に、「検索ワード」を含むファイル名がフルパスで出力します。
並列処理と非並列処理の処理時間を比較するために、それぞれの結果を出力するようにしています。

2023-03-07 04:55 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml
> +
コントロールの命名も意識してみてください。
1つの画面内に同じ種類のコントロールが複数存在するとき、見分けがつくようにしておく必要があります。
命名方法は、「コントロール名+表すもの」が理想です。
いつもの変数の命名に、コントロール名を先頭につける形です。
Gaia Cloudでは、コントロール名の部分をアルファベット三文字（例：Button = Btn、TextBox = Txt、Label = Lblなど）で表していることが多いです。
つまり、ファイル選択ボタンなどは「BtnSelectFile」、ファイル読み込みラベルなどは「LblReadFile」などが良いかと思います。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            IList<string> wLines = await FileIO.ReadLinesAsync(wFile);
課題の要件に「StreamReaderクラスのReadLinesAsyncメソッドを使う」とあります。
もちろん、別の方法で実装してもらうのも良いことですが、まずは要件を満たすような実装をしてみてください。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            return wLines;
この3行は1行で書き直すことができます。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            wOpenPicker.FileTypeFilter.Add(".txt");
wOpenPicker.FileTypeFilterの要素が変化する予定がない場合は、初期化子で定義しておくほうが保守性が高いです。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            }
nullかnullじゃないかの二択なので、三項演算子で書いてしまっても良いです。
また、空の文字列は`String.Empty`を用いるようにすると可読性がUPするのでおすすめです。
役割は`""`と全く同じです。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            }
1行で書き直してみてください。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            wFbDialog.SelectedPath = @"C:";
初期化子で定義してしまってよいです。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +        }
不要なコードは削除してください。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            label13.Text = wNormalText.Item2;
検索結果は同じになるのでテキストボックスは1つで良いと思うのですが、分けた理由はありますか？
また、テキストボックスが編集可能状態です。検索結果は読み取り専用であること理想だと思います。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            InitializeComponent();
コントロールの配置についてです。
ユーザーの目線の動きを意識してみてください。
通常、画面を見るとき、英文を読むときと同様に左から右へ、上から下へ目線を運びます。

理想的なUIは、「説明がなくてもその画面をみただけで何をしたらいいかわかる」と言われています。
初見のユーザーでも迷わずに操作できるような画面構成を考えてみると良いです！

参考までに、私なりに画面を少し手直ししてみました。↓

![image](https://user-images.githubusercontent.com/86827185/223319954-24308b11-ac96-43f4-8abf-df91a7e7279f.png)

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            };
追加する文字列ごとに改行を加えたい場合は、AppendLineメソッドが使えます。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            StringBuilder wPath = new StringBuilder();
varでよいです。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +        private (StringBuilder, string) NormalReadLine() {
このメソッドの呼び出し元では戻り値をStringBulderとして使用されないので、stringで返しておくほうがメソッドの役割が明確になります。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            var wNormalRun = Task.Run(() => NormalReadLine());
変数宣言は不要です。

2023-03-07 04:55 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            IEnumerable<string> wFiles = Directory.EnumerateFiles(textBox3.Text, "*", SearchOption.AllDirectories);
問題には、C#のソースファイルを検索するとあります。
テキストファイルなども検索対象となっているので修正してください。

2023-03-07 08:27 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml
> +
承知しました。
GaiaCloudに沿って、変更しました。

2023-03-08 02:45 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            IList<string> wLines = await FileIO.ReadLinesAsync(wFile);
StreamReaderクラスのReadLinesAsyncメソッドを使って、実装しなおしました。

2023-03-08 03:04 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            return wLines;
FileIOクラスのReadLinesAsyncメソッドを使わずに、StreamReaderクラスのReadLinesAsyncメソッドを使って実装しなおしたため、コードが変わりました。
そのため、修正していません。

2023-03-08 03:42 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            wFbDialog.SelectedPath = @"C:";
初期化子で定義しました。

2023-03-08 03:44 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            label13.Text = wNormalText.Item2;
一応、正常に動いていることを示したかったので、両結果を出力しました。
不要でしたので、削除しました。

結果をreadonlyにしました。

2023-03-08 03:48 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            };
AppendLineメソッドでやり直しました。

2023-03-08 03:49 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            StringBuilder wPath = new StringBuilder();
varにしました。

2023-03-08 03:51 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +        private (StringBuilder, string) NormalReadLine() {
stringに変更しました。

2023-03-08 03:56 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            }
一行で書き直しました。

2023-03-08 03:57 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +        }
削除しました。

2023-03-08 09:34 UTC, ko-kato-being requested changes

2023-03-08 09:34 UTC, ko-kato-being commented on chapter16/Question16-2/Form1.cs
> +            }
FolderBrowserDialog は IDisposable インターフェースを実装しているので、使い終わった時点で確実に dispose する必要があります。
今回の場合は↓のように using を使うことで確実に dispose することができます。
```
using (FolderBrowserDialog wFbDialog = new FolderBrowserDialog()) {
    wFbDialog.Description = "検索するディレクトリの選択";
    wFbDialog.SelectedPath = @"C:";
    if (wFbDialog.ShowDialog() == DialogResult.OK) {
        return wFbDialog.SelectedPath;
    } else {
        return "キャンセルされました";
    }
};
```
画面上に表示されるコンポーネント類は基本的に IDisposable を実装しています。
なので、上記のコードは定石として覚えておくと良いです。

余談ですが、バグの原因としてリソースの解放漏れは比較的に多い部類です。
確保したリソースを忘れず解放する癖を身に着けたいですね。
使っているクラスがリソースを使用するのかどうかをまずは意識していきましょう。

具体的な行動として

- 未知のクラスのインスタンスを生成する際には、まずクラスの定義を確認します。
- 子クラスの場合は親クラスをどんどんさかのぼって、IDisposable を実装しているかどうかを確認します。

あと、ついでに気になったのですが、キャンセルボタンを押したら「キャンセルされました」という文字列を返すのは設計として微妙な気がします。
このメソッドの責務を考えてみてください。

2023-03-09 02:14 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            wOpenPicker.FileTypeFilter.Add(".txt");
初期化子を使って、定義するように修正しました。

2023-03-09 02:24 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            }
それぞれ三項演算子を使って、書きました。
２行になっています。

2023-03-09 02:27 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            InitializeComponent();
参考にして、作り直しました！
説明がなくても画面を見ただけで何をしたらいいかわかる、意識していきます！！

2023-03-09 02:41 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            IEnumerable<string> wFiles = Directory.EnumerateFiles(textBox3.Text, "*", SearchOption.AllDirectories);
EnumerateFilesメソッドの第二引数を*.csにして、修正しました。

2023-03-09 05:30 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            }
コメント、ありがとうございます。
「IDisposable インターフェースを実装しているクラス」や「親クラスがIDisposable インターフェースを実装しているクラス」では、リソースの開放を明示的に行う必要があるんですね。勉強になります！
未知のクラスを使う際には、クラスの定義を確認していきます。
分かりやすい説明と具体的な行動、助かります。
定石に従って、修正しました。

メソッドの責務、考えてみました。
SelectDirectory（旧：ChoiceDirectory）メソッドは、Directoryを選択するためのメソッドであって、どれかのテキストに文字列を代入するためのメソッドではないです。
なので、キャンセルしたときに「キャンセルされました」という文字列を返すのは、おかしかったです。
nullを返すように修正しました。

2023-03-09 05:55 UTC, ko-kato-being commented on chapter16/Question16-2/Form1.cs
> +            }
修正ありがとうございました。

> SelectDirectory（旧：ChoiceDirectory）メソッドは、Directoryを選択するためのメソッドであって、どれかのテキストに文字列を代入するためのメソッドではないです。
> なので、キャンセルしたときに「キャンセルされました」という文字列を返すのは、おかしかったです。
> nullを返すように修正しました。
この修正は良いかんじだと思います！
ヘッダのコメントも合わせて修正しておくとさらに良いですね。
まず前提として、null が返るケースがある場合は必ず明示するようにしてください。
これはメソッド使う側で null チェックが必要かどうかを判断するためです。
今回の場合は、どういった時に null が返るかを説明しておくと良いですね。

このメソッドを呼び出している側も修正しておいた方が良いですね。
null が返ってきてもそのままテキストボックスに代入されています。
フォルダ選択画面をキャンセルした時に、テキストボックスが空で更新されませんか？
「キャンセル」ボタンを押したのに何か更新されるのはNGですね。
画面をOK以外で閉じた場合は何もしないのが良いです。
そうなると、SelectDirectory というメソッドが不要になりそうです。

2023-03-09 07:30 UTC, k-miyahara-being reviewed
修正お願いします。

2023-03-09 07:30 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            IEnumerable<string> wLines = await ReadLines(TxtFilePath.Text);
型をIEnumerableにしているのは理由がありますか？
ReadLinesメソッドの戻り値の型を見直してみてください。

2023-03-09 07:30 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            TxtShowText.Text = wLines == null ? String.Empty : String.Join("\n", await ReadLines(TxtFilePath.Text));
https://github.com/ohdaira-being/textC-/pull/16#discussion_r1130514979
上記と同様に、ファイル選択でキャンセルしたときに前にテキストボックスが空になります。
前の状態を維持するように修正をお願いします。

2023-03-09 07:30 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            wFbDialog.SelectedPath = @"C:";
こちら未修正です。

2023-03-09 07:30 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            };
`wPath`と`wFile`の変数名を考え直してみてください。

2023-03-10 06:38 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            wFbDialog.SelectedPath = @"C:";
すみません。
修正しました。

2023-03-10 08:01 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            IEnumerable<string> wLines = await ReadLines(TxtFilePath.Text);
理由はありません。
ReadLinesメソッドは、ファイルを読み込んで、読み込んだ内容を返すメソッドなので、戻り値の型はstringが適していました。
ReadLinesメソッドの戻り値をstringに変更しました。

2023-03-10 08:09 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +            TxtShowText.Text = wLines == null ? String.Empty : String.Join("\n", await ReadLines(TxtFilePath.Text));
ファイル選択をキャンセルしたときは、テキストボックスに代入しないように修正しました。

2023-03-10 08:17 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            };
wPathは、条件に合ったファイルパスを複数格納するので、wPaths
wFileは、読み込むファイルのパスを表すので、wPath
としました。

2023-03-10 08:51 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            }
前提として、メソッド使う側で null チェックが必要かどうかを判断するために、null が返るケースがある場合は必ず明示する必要があるんですね。
ありがとうございます！

フォルダ選択画面をキャンセルした時に、テキストボックスが空で更新されています。
「キャンセル」ボタンを押したら、何も処理がされないようにしなければいけなかったです。
if文を使って、キャンセル処理を追加しました。

2023-03-13 01:36 UTC, ko-kato-being commented on chapter16/Question16-2/Form1.cs
> +            }
修正ありがとうございました。
リファクタリングでかなりコード良くなっています！
ですが、もう少しだけ修正の余地があるかな。

>「キャンセル」ボタンを押したら、何も処理がされないようにしなければいけなかったです。

これが仕様なら、いまのコードは若干異なる動きになっています。
例えば、空のパスを指定してOKした時もテキストボックスが更新されないはずです。
※UI上ではこの操作はできないかもですが

私だったらこう書くかなという例を載せておきます。
```
private void BtnSelectFile_Click(object sender, EventArgs e) {
    using (var wFbDialog = new FolderBrowserDialog()) {
        wFbDialog.Description = "検索対象（ファルダ）の選択";
        wFbDialog.SelectedPath = @"C:";
        if (wFbDialog.ShowDialog() != DialogResult.OK) return;
        TxtDirectoryPath.Text = wFbDialog.SelectedPath;
    }
}
```
「キャンセルした時に処理しない」をストレートに表現するとこうなりますかね。
SelectDirectory() というメソッドがそもそも無くて良い気がします。
参照が1つしかないメソッドは基本的に不要です。
※可読性を上げるためにあえてメソッドに切り出すことはたまにあります。

2023-03-13 01:52 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            wFbDialog.SelectedPath = @"C:";
Slackで加藤さんがご指摘の通り、`"検索対象（ファルダ）の選択"`の誤字修正をお願いします。

2023-03-13 01:54 UTC, k-miyahara-being commented on chapter16/Question16-2/Form1.cs
> +            };
`wFiles.AsParallel().Where(x => IsMatchText(x, textBox1.Text) && IsMatchText(x, textBox2.Text)`はそこまで長くないので改行しなくてもよいかなと思います。

2023-03-13 04:01 UTC, k-miyahara-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +        }
メソッド同士の間は詰めず空行をいれると見やすいと思います。

2023-03-14 02:35 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            };
一行で書き直しました。

2023-03-14 02:35 UTC, ohdaira-being commented on chapter16/Question16-1/MainWindow.xaml.cs
> +        }
メソッド間に空行を入れるようにしました。

2023-03-14 04:01 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            }
コメントありがとうございます。
空のパスを指定した場合を考えられていませんでした。
今までは、「キャンセルしたとき」ではなく「空のパスを指定したとき」にテキストボックスを更新しないという実装でした。
また、目的もなくメソッドにしてしまっていました。
例でいただいたコードに修正しました。

2023-03-14 04:48 UTC, k-miyahara-being approved these changes

2023-03-14 07:05 UTC, ko-kato-being requested changes

2023-03-14 07:05 UTC, ko-kato-being commented on chapter16/Question16-2/Form1.cs
> +            }
こうする方が使いやすいんじゃないかという提案です。
検索ボタンを押した時にパスをチェックするのではなく、ファイル選択画面でOKを押した時点でチェックした方が良いと思います。
ユーザーとしては、

- パスを選択する
- 検索ボタンを押す
- パスが間違っていると怒られる
→ならパスを選択した時点で教えてほしい

となるかと思います。
ちなみに、今回のように入力内容に問題がないかチェックすることを「バリデーション (validation)」と呼びます。
この言葉はプログラミングにおいてよく出てくるので覚えておいてください。

2023-03-14 10:12 UTC, ohdaira-being commented on chapter16/Question16-2/Form1.cs
> +            }
コメント、ありがとうございます。
修正内容の「ファイル選択画面でOKを押した時点でパスが間違える」ケースがあまりイメージできませんでした。
FolderBrowserDialogでは、存在しないパスやごみ箱のようなフォルダーは、選択できずコードを書いても動作を確認できないので、教えていただきたいです。

「パスを選択した時点で教えてほしい」という実装は、TxtDirectoryPath_TextChangedイベントでテキストボックスに入れたパスが存在するかどうか常に判別するようにしました。
存在しない場合、テキストカラーを赤色、検索ボタンを無効、
存在する場合、テキストカラーを黒色、検索ボタンを有効、とすることでバリデーションを行うようにしました。

バリデーションをどこで行うべきかが難しそうですが、今後意識していこうと思います！

2023-03-14 11:36 UTC, ko-kato-being commented on chapter16/Question16-2/Form1.cs
> +            }
修正ありがとうございます。
工夫して実装してもらったようで、良い感じになったんじゃないでしょうか。
ユーザー目線を今後も意識していけると良いですね。

2023-03-15 23:58 UTC, merged