17章　章末問題
odaira1119/textC- pull request #17
Opened 2023-03-13 09:16 UTC by ohdaira-being

編集ファイル
・TextFileProcessor.sln
・TextProcessor.cs
・TextProcessor.dll（作成したフレームワーク）
・Question17-1/ToHankakuProcessor.cs
・Question17-2/ConverterBase.cs
・Question17-2/ConverterFactory.cs
・Question17-2/DistanceConverter.cs
・Question17-3/ITextFilesService.cs
・Question17-3/TextFileProcessor.cs
・Question17-3/TohankakuService.cs

2023-03-14 04:42 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-1/ToHankakuProcessor.cs
> +        }
Execute、Terminateともにforeachで同じ行を回すということは、計算量が2倍になるということです。（行数が多いほど差は大きくなる）
Execute内で出力処理も同時にしてしまったほうがより効率的だと思います。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Sample17-1.txt
> +It's ２０２３
テストケースとしては少し不十分かと思います。以下のようなケースも追加して確認してみてください。
・1行に半角全角数字が混在するケース
・郵便番号、電話番号のような数字と記号が混在 + 半角全角が混在するケース
・⑪⑷のような記号数字

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public abstract bool IsMyUnit(string vName);
引数の説明：単位→単位名
戻り値の説明：何の真偽か具体的にわかるように補足してください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public abstract string UnitName { get; }
コメントとプロパティ名が合致していません。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterBase.cs
> +    public abstract class ConverterBase {
クラスの説明を書いてください。
他のクラスも同様です。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public double FromMeter(double vMeter) => vMeter / Ratio;
thisを付けてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public double ToMeter(double vFeet) => vFeet * Ratio;
引数名がフィートに限定された名前になっています。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterFactory.cs
> +        private static ConverterBase[] FConverters = new ConverterBase[]{
`]`と`{`の間に空白を入れてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/DistanceConverter.cs
> +        public ConverterBase To { get; private set; }
プロパティの説明を書いてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/DistanceConverter.cs
> +            return To.FromMeter(wMeter);
thisを付けてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/Program.cs
> +            double? wValue = null;
メソッド間に空行を入れてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/Program.cs
> +            } while (wValue == null);
do while文をwhile文で書き直してみてください。
可読性の観点から、do while文は使わない、という暗黙のルールがあったりします。
詳しくはリーダブルコード7.4節を読んでみてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/Program.cs
> +        static ConverterBase GetConverter(string vMsg) {
変数名は1単語の場合、無理に略さずそのままのほうが分かりやすいです。
vMessage

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-2/Program.cs
> +                Console.WriteLine(vMsg + " => ");
`=>` で矢印で差した先に入力できたほうがユーザーにとって分かりやすいと思います。
また、入力が不正であった場合のメッセージも出力してあげるとよりユーザーにやさしいです。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-3/ITextFilesService.cs
> +        void Terminate();
何のインターフェースなのかの説明と、各メソッドの説明を追加してください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-3/TextFileProcessor.cs
> +            this.FService.Initialize(vFileName);
引数の説明と名前が合致しません。
また、コーディング規約に従ってフィールド変数にはthisはつけなくてよいです。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-3/TextFileProcessor.cs
> +                while(!wSr.EndOfStream){
変数名から何を表すものかイメージできないため、命名し直してみてください。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-3/TohankakuService.cs
> +        }
引数の説明と名前が合致していません。
また、空のメソッドは改行せず1行で書いておきましょう。

2023-03-14 04:42 UTC, k-miyahara-being commented on chapter17/Question17-3/TohankakuService.cs
> +        }
と同じです。

2023-03-15 01:07 UTC, ohdaira-being commented on chapter17/Question17-1/ToHankakuProcessor.cs
> +        }
フィールド変数の型をList<string>からStringBuilderに変更し、Terminate内では純粋にフィールド変数を出力するように修正しました。

2023-03-15 01:08 UTC, odaira1119 commented on chapter17/Sample17-1.txt
> +It's ２０２３
以下の文字列を追加しました。
０６０－６514-９９０８
887-9490
①８８７ー8778
⑵８７7-11１９

2023-03-15 01:28 UTC, ohdaira-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public double FromMeter(double vMeter) => vMeter / Ratio;
Ratioにthisを付けました。

2023-03-15 01:29 UTC, ohdaira-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public double ToMeter(double vFeet) => vFeet * Ratio;
vDistanceに変更しました。

2023-03-15 01:34 UTC, ohdaira-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public abstract bool IsMyUnit(string vName);
ヘッダコメントを見直しました。

2023-03-15 01:35 UTC, ohdaira-being commented on chapter17/Question17-2/ConverterBase.cs
> +        public abstract string UnitName { get; }
単位名プロパティに変更しました。
また、ほかのプロパティのヘッダコメントも見直しました。

2023-03-15 01:35 UTC, ohdaira-being commented on chapter17/Question17-2/ConverterBase.cs
> +    public abstract class ConverterBase {
記載しました。

2023-03-15 01:36 UTC, ohdaira-being commented on chapter17/Question17-2/ConverterFactory.cs
> +        private static ConverterBase[] FConverters = new ConverterBase[]{
空白を入れました。

2023-03-15 01:37 UTC, ohdaira-being commented on chapter17/Question17-2/DistanceConverter.cs
> +        public ConverterBase To { get; private set; }
追加しました。

2023-03-15 01:38 UTC, ohdaira-being commented on chapter17/Question17-2/DistanceConverter.cs
> +            return To.FromMeter(wMeter);
thisを追加しました。

2023-03-15 01:39 UTC, ohdaira-being commented on chapter17/Question17-2/Program.cs
> +            double? wValue = null;
すべてのメソッド間を確認して、空行を入れました。

2023-03-15 01:39 UTC, ohdaira-being commented on chapter17/Question17-2/Program.cs
> +        static ConverterBase GetConverter(string vMsg) {
承知しました。

2023-03-15 02:07 UTC, ohdaira-being commented on chapter17/Question17-2/Program.cs
> +            } while (wValue == null);
do while文をwhile文で書き直しました。

2023-03-15 02:43 UTC, ohdaira-being commented on chapter17/Question17-2/Program.cs
> +                Console.WriteLine(vMsg + " => ");
=>を削除し、指示文中に「次の行に入力する」ことを追記しました。
また、入力を間違えた場合、入力が間違えていることを伝えるメッセージを表示するようにしました。

2023-03-15 02:44 UTC, ohdaira-being commented on chapter17/Question17-3/TextFileProcessor.cs
> +            this.FService.Initialize(vFileName);
thisを削除しました。

2023-03-15 02:49 UTC, ohdaira-being commented on chapter17/Question17-3/TextFileProcessor.cs
> +                while(!wSr.EndOfStream){
wStreamReaderに変更しました。

2023-03-15 02:50 UTC, ohdaira-being commented on chapter17/Question17-3/TohankakuService.cs
> +        }
一行にしました。

2023-03-15 02:59 UTC, ohdaira-being commented on chapter17/Question17-3/ITextFilesService.cs
> +        void Terminate();
説明を追加しました。

2023-03-15 09:28 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterFactory.cs
> +    static class ConverterFactory {
どんなインスタンスを生成するクラスかわかるとより良いです。

2023-03-15 09:28 UTC, k-miyahara-being commented on chapter17/Question17-2/Program.cs
> +                Console.WriteLine(vMsg + " => ");
OKです。

[補足]
Console.WriteLineメソッドは、文字列＋改行 で出力されますが、
Console.Writeメソッドを使うと、改行がされなくなるので次の行ではなくその行に入力できるようになります。

2023-03-15 09:40 UTC, k-miyahara-being commented on chapter17/Question17-3/TohankakuService.cs
> +        /// 初期値設定クラス
クラスではなくメソッドですかね？

2023-03-15 09:40 UTC, k-miyahara-being commented on chapter17/Question17-2/ConverterFactory.cs
> +    static class ConverterFactory {
どんなインスタンスを生成するクラスかわかるとより良いです。

2023-03-15 09:40 UTC, k-miyahara-being commented on chapter17/Question17-2/Converters/FeetConverter.cs
> +        protected override double Ratio { get { return 0.3048; } }
簡略化できます。
他の箇所も同様です。

2023-03-15 09:40 UTC, k-miyahara-being commented on chapter17/Question17-2/Converters/FeetConverter.cs
> +        public override bool IsMyUnit(string vName) => vName.ToLower() == "feet" || vName == UnitName;
UnitNameにthisを付けてください。
他の箇所も同様です。

2023-03-15 09:56 UTC, ohdaira-being commented on chapter17/Question17-2/Program.cs
> +                Console.WriteLine(vMsg + " => ");
Console.Writeメソッドだと、そのようにできたんですね。
ありがとうございます！

2023-03-15 09:58 UTC, ohdaira-being commented on chapter17/Question17-3/TohankakuService.cs
> +        /// 初期値設定クラス
何かと間違えました。
コメントを書き直しています。

2023-03-15 10:01 UTC, odaira1119 commented on chapter17/Question17-2/ConverterFactory.cs
> +    static class ConverterFactory {
書き直しました。

2023-03-15 10:04 UTC, ohdaira-being commented on chapter17/Question17-2/Converters/FeetConverter.cs
> +        protected override double Ratio { get { return 0.3048; } }
式本体をしようして、簡略化しました。

2023-03-15 10:04 UTC, ohdaira-being commented on chapter17/Question17-2/Converters/FeetConverter.cs
> +        public override bool IsMyUnit(string vName) => vName.ToLower() == "feet" || vName == UnitName;
thisを付けました。

2023-03-16 01:30 UTC, k-miyahara-being commented on chapter17/Question17-3/TohankakuService.cs
> +    public class TohankakuService : ITextFilesService {
`TohankakuService` の hが小文字になっています。
ファイル名も修正をおねがいします。

2023-03-16 02:44 UTC, ohdaira-being commented on chapter17/Question17-3/TohankakuService.cs
> +    public class TohankakuService : ITextFilesService {
気づきませんでした。変更しています。

2023-03-16 02:51 UTC, k-miyahara-being commented on chapter17/Question17-3/TohankakuService.cs
> +    public class TohankakuService : ITextFilesService {
ファイル名が変わっていませんが、OKとします。

2023-03-16 02:52 UTC, k-miyahara-being approved these changes

2023-03-16 04:59 UTC, merged