chapter2の演習問題を提出します。
odaira1119/textC- pull request #2
Opened 2023-01-10 06:23 UTC by ohdaira-being

問題数3問でした。
2-3は、Program.csの「商品カテゴリ別集計」とSalesCounter.csの「商品カテゴリ別の売上を求める」が問題の解答になっています。

2023-01-16 05:27 UTC, k-miyahara-being requested changes

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +        }
引数名をわかりやすく変更してください。
Gaia Cloudのコーディング規約にも注意してください。

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +                (song3.Title, song3.ArtistName, song3.Length)};
書き方が冗長なので、[初期化子](https://learn.microsoft.com/ja-jp/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers)を使ってリファクタリングしてみましょう。
配列の型はobject型である必要はないです。

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +    public class Song {
クラスをファイルに分けてみてください。

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-2/Program.cs
> +            Console.WriteLine("Hello World!");
不要なコードは削除してください。

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-2/Program.cs
> +            }
サンプルプログラムでは、換算を行うメソッドに分けていると思うので、この課題でもMainからメソッドを分離してみましょう。
出力部分ですが、単位がフィートになっています。
また、文字列補完式を使って書いてみましょう。

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-3/Program.cs
> +            var sales = new SalesCounter("sales.csv");
読み込んでいるcsvファイルはどこにありますか？

2023-01-16 05:27 UTC, k-miyahara-being commented on chapter2/Question2-3/SalesCounter.cs
> +        private IEnumerable<Sale> _sales;
サンプルプログラムですが、こちらもGaia Cloudのコーディング規約に沿って変数名を修正してみてください。

2023-01-16 07:31 UTC, ohdaira-being commented on chapter2/Question2-1/Program.cs
> +        }
x→vTitle
y→vArtistName
z→vLength
に変更しました。

2023-01-16 07:32 UTC, ohdaira-being commented on chapter2/Question2-1/Program.cs
> +                (song3.Title, song3.ArtistName, song3.Length)};
型をSongにし、インスタンス生成を配列内で直接するようにしました。

2023-01-16 07:33 UTC, ohdaira-being commented on chapter2/Question2-1/Program.cs
> +    public class Song {
Song.csファイルにSongクラスを定義しました。

2023-01-16 07:34 UTC, ohdaira-being commented on chapter2/Question2-2/Program.cs
> +            Console.WriteLine("Hello World!");
Console.WriteLine("Hello World!");
を削除しました。

2023-01-16 07:43 UTC, ohdaira-being commented on chapter2/Question2-2/Program.cs
> +            }
新しく静的なメソッドのPrintInchToMeterListメソッドを作りました。
引数を整数型のvStartとvStopとしました。

単位をinchに書き直しました。
文字列補間式で記述しました。

2023-01-16 07:46 UTC, ohdaira-being commented on chapter2/Question2-3/Program.cs
> +            var sales = new SalesCounter("sales.csv");
bin/Debug/netcoreapp3.1内にあります。
プッシュできていませんでした、申し訳ありません。

2023-01-16 07:56 UTC, ohdaira-being commented on chapter2/Question2-3/SalesCounter.cs
> +        private IEnumerable<Sale> _sales;
chapter2のファイル全てにGaia Cloudのコーディング規約と文字列補間式を適用しました。

2023-01-17 06:23 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +        }
OKです。

2023-01-17 06:25 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +                (song3.Title, song3.ArtistName, song3.Length)};
OKです。

2023-01-17 06:38 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +    public class Song {
クラス、プロパティ、コンストラクタにコメント`<summary>`を付けて、何を表すものかを示してみてください。
1つ上の行で`///`と入力すると自動でsummaryタグが入力されます。
コンストラクタやメソッドに対して`///`を入力すると、引数や戻り値のコメントを書くためのタグも自動入力されます。
第三者がみて、
・どのようなクラスで
・どのようなプロパティを持っていて
・コンストラクタには何が渡されるのか、
といったことをすぐに理解できるようにしておく意図があります。
publicなメソッドにもつけることが多いです。
↓↓↓例

```
    /// <summary>
    /// 曲クラス
    /// </summary>
    public class Song {
        /// <summary>
        /// 曲のタイトル
        /// </summary>
        public string Title { get; set; }  
        /// <summary>
        /// アーティスト名
        /// </summary>
        public string ArtistName { get; set; }
        /// <summary>
        /// 曲の長さ
        /// </summary>
        public int Length { get; set; }  

        /// <summary>
        /// コンストラクタ
        /// </summary>
        /// <param name="vTitle">曲のタイトル</param>
        /// <param name="vName">アーティスト名</param>
        /// <param name="vLength">曲の長さ</param>
        public Song(string vTitle, string vName, int vLength) {
　　　 　　　：
```

2023-01-17 06:38 UTC, k-miyahara-being commented on chapter2/Question2-2/Program.cs
> +            Console.WriteLine("Hello World!");
OKです。

2023-01-17 06:39 UTC, k-miyahara-being commented on chapter2/Question2-2/Program.cs
> +            }
OKです。

2023-01-17 06:39 UTC, k-miyahara-being commented on chapter2/Question2-3/Program.cs
> +            var sales = new SalesCounter("sales.csv");
OKです。

2023-01-17 06:46 UTC, k-miyahara-being requested changes

2023-01-17 06:46 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +                Console.WriteLine(s);
正しく出力されていません。
時間の表示方法にも気を付けて修正してください。

また、foreach内で使用される`s`もローカル変数です。
適切な名前と接頭辞をつけてください。
そして、型も明示的なものに変更してください。

2023-01-17 07:58 UTC, ohdaira-being commented on chapter2/Question2-1/Program.cs
> +                Console.WriteLine(s);
変数名をwSongに変更し、時間の表示をTimespanコンストラクタを使って実装し直しました。

2023-01-17 08:06 UTC, ohdaira-being commented on chapter2/Question2-1/Program.cs
> +    public class Song {
<summary>を付けて、それぞれが示す内容を表しました。

2023-01-18 05:24 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +    public class Song {
プロパティについてはOKです。
コンストラクタとメソッドについて、引数と戻り値の説明がされていないです。
↑の例を参考にして書いてみてください。
また、クラスに対しても何を表すクラスかコメントしてください。（自作したクラスのみでOK）

2023-01-18 05:25 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +                Console.WriteLine(s);
ここだけでなく、他のforeach文でも同様に修正されているかチェックしてください。

2023-01-18 09:10 UTC, odaira1119 commented on chapter2/Question2-1/Program.cs
> +    public class Song {
説明を追加しました。

2023-01-18 09:11 UTC, ohdaira-being commented on chapter2/Question2-1/Program.cs
> +                Console.WriteLine(s);
修正漏れしていたforeach文を修正しました。

2023-01-18 10:55 UTC, k-miyahara-being approved these changes

2023-01-18 10:55 UTC, k-miyahara-being commented on chapter2/Question2-1/Program.cs
> +                Console.WriteLine(s);
OKです。

2023-01-18 10:55 UTC, k-miyahara-being commented on chapter2/Question2-3/SalesCounter.cs
> +        private IEnumerable<Sale> _sales;
OKです。

2023-01-18 11:06 UTC, k-miyahara-being requested changes

2023-01-18 11:06 UTC, k-miyahara-being commented on chapter2/Question2-1/Song.cs
> +        public string Length { get; set; }
Lengthプロパティの型はもともとintだったと思います。
長さを表すものとしても、数値型であることが望ましいのでこれは変えないようにしましょう。

また、コンストラクタではなく出力時に指定された書式になるように修正すればよいと思います。

2023-01-19 00:15 UTC, ohdaira-being commented on chapter2/Question2-1/Song.cs
> +        public string Length { get; set; }
intに修正しました。
コンストラクタで出力の表示書式（〇〇：●●書式）に変換していたので、出力側でやるように修正しました。

2023-01-19 01:33 UTC, k-miyahara-being approved these changes
レビューOKです。

2023-01-19 02:53 UTC, merged