chapter3の演習問題を提出します。
odaira1119/textC- pull request #3
Opened 2023-01-11 01:52 UTC by ohdaira-being

大問２問でそれぞれ小問が４問ありました。

2023-01-16 06:06 UTC, k-miyahara-being requested changes

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +            Console.WriteLine(exists);
変数宣言は不要ですね。
直接書いてしまえば1行で済みます。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +                Console.WriteLine(s);
ここも変数宣言は不要です。
また、varを使うことは間違いではありませんが、対象から推測できない場合は明示的に書いておくほうが親切で可読性も上がります。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +            var number = new List<int> { 12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48 };
Listや配列などのコレクションの変数名は複数形であることが好ましいです。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            };
変数名は複数形が好ましいです。
30行目のインデントがずれています。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
[FindIndexメソッド](https://learn.microsoft.com/ja-jp/dotnet/api/system.collections.generic.list-1.findindex?view=netframework-4.6.1)は、対象が見つからなかった場合-1を返すようになっているのでこの分岐は不要です。
ライブラリが用意してくれているメソッドは、メソッドにカーソルを当ててF12キーで定義をみることができます。
定義には、そのメソッドの引数や戻り値について書かれているので使用するときは一度見てみると良いです。
F1キーで公式ドキュメントに飛ぶのでそちらで確認しても良いと思います。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            Console.WriteLine(count);
変数宣言なしで1行で書いてしまいましょう。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(s);
for文やforeach文は、中身が1行であっても中括弧{}で囲ってあるほうが読みやすいです。
意図しない箇所がループしてしまうことを防ぐためにも、書いておくことが無難です。

2023-01-16 06:06 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            var firstBstring = name.Where(s => s.Substring(0,1) == "B").Select(s => s.Length);
先頭の文字を取得するためにSubstringメソッドを使ってもらっていますが、より[シンプルな方法](https://dobon.net/vb/dotnet/string/stringchars.html)があります。
書き換えてみてください。

2023-01-16 08:20 UTC, ohdaira-being commented on chapter3/Question3-1/Program.cs
> +            Console.WriteLine(exists);
着雪描いた方がいい箇所は、直接書くようにしました。

2023-01-16 08:21 UTC, ohdaira-being commented on chapter3/Question3-1/Program.cs
> +                Console.WriteLine(s);
直接書きました。

varをintで書き直しました。

2023-01-16 08:27 UTC, ohdaira-being commented on chapter3/Question3-1/Program.cs
> +            var number = new List<int> { 12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48 };
複数形で書き直しました。

2023-01-16 08:31 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +            };
wNamesに書き直しました。

インデントを追加しました。

2023-01-16 08:36 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
なるほどです。
定義を確認して使うようにします。

不要なコードを削除しました。

2023-01-16 08:39 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +            Console.WriteLine(count);
直接書くようにしました。

2023-01-16 08:41 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(s);
なるほどです。
中括弧を追加しました。

2023-01-16 09:07 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +            var firstBstring = name.Where(s => s.Substring(0,1) == "B").Select(s => s.Length);
こんなシンプルにできるなんて驚きました。
String.Charsプロパティを使って、書き直しました。

2023-01-17 06:52 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +            Console.WriteLine(exists);
OKです。

2023-01-17 06:53 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +                Console.WriteLine(s);
foreach内の変数`s`も適切な名前に変更してください。

2023-01-17 06:54 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +            var number = new List<int> { 12, 87, 94, 14, 53, 20, 40, 35, 76, 91, 31, 17, 48 };
OKです。

2023-01-17 06:55 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            };
OKです。

2023-01-17 06:56 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
見つからなかったとき何も出力されないコードになっています。

2023-01-17 06:57 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            Console.WriteLine(count);
OKです。

2023-01-17 06:58 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(s);
https://github.com/ohdaira-being/textC-/pull/3#discussion_r1071801962 と同じです。

2023-01-17 06:59 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            var firstBstring = name.Where(s => s.Substring(0,1) == "B").Select(s => s.Length);
https://github.com/ohdaira-being/textC-/pull/3#discussion_r1071801962 と同じです。

2023-01-17 09:37 UTC, ohdaira-being commented on chapter3/Question3-1/Program.cs
> +                Console.WriteLine(s);
sをwNumberに書き直しました。

2023-01-17 09:46 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
wIndexが０番目から始まっていたので、1番目から数えるように修正しました。
また、見つからなかった場合、ー１を出力するように修正しました。

2023-01-17 09:48 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(s);
wNameに書き直しました。

2023-01-17 09:48 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +            var firstBstring = name.Where(s => s.Substring(0,1) == "B").Select(s => s.Length);
wNamesに書き直しました

2023-01-18 05:51 UTC, k-miyahara-being commented on chapter3/Question3-1/Program.cs
> +                Console.WriteLine(s);
OKです。

2023-01-18 05:55 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
ｗLineの変数宣言は不要ですね。

> wIndexが０番目から始まっていたので、1番目から数えるように修正しました。

問題の解釈の話になってくるのでそれでもOKとします。
ただ、今のままだとTokyoと入力したときの出力が0になると思います。

2023-01-18 05:56 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(s);
OKです。

2023-01-18 05:56 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +            var firstBstring = name.Where(s => s.Substring(0,1) == "B").Select(s => s.Length);
OKです。

2023-01-18 09:18 UTC, ohdaira-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
wlineの変数宣言を削除しました。

if文の条件が誤っており、0より大きい数字から0以上の条件に修正しました。

2023-01-18 10:52 UTC, k-miyahara-being approved these changes

2023-01-18 10:53 UTC, k-miyahara-being commented on chapter3/Question3-2/Program.cs
> +                Console.WriteLine(-1);
OKです。

2023-01-19 00:41 UTC, merged

2023-01-19 04:45 UTC, ko-kato-being commented on chapter3/Question3-2/Program.cs
> +            }
@ohdaira-being CC @k-miyahara-being 
[String.StartsWith メソッド](https://learn.microsoft.com/ja-jp/dotnet/api/system.string.startswith?view=net-7.0) を使うというのも選択肢の一つですね。
知らなかったら調べてみてください。
※修正は不要です。