chapter4の演習問題を提出します。
odaira1119/textC- pull request #4
Opened 2023-01-17 10:28 UTC by ohdaira-being

1回目の提出です。

2023-01-19 02:38 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Month { get; private set; }
privateなので外部からは読み取り専用になっていますが、YearMonthクラス内では書き換え可能になっています。
コンストラクタで値を設定した後、どこからも書き換えられたくない（読み取り専用にしたい）場合は、getterのみにするという方法があります。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
名前から察するに、「21世紀かどうか」を表すプロパティだと思います。
このプロパティの目的と持つべき値をもう一度考えなおしてみてください。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +            if (Month == 12) {
可読性に関するものです。
クラス内のプロパティを使用するときは、thisを付けておくと、その他の変数や引数と区別がしやすいです。
コンストラクタに書く時と同じ感じです。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +                Month = 1;
12月のとき、値を変えるのは月だけで良いですか？

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +            //ここを実装する
不要なコメントは削除してください。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +            return StringDay;
変数宣言は不要です。
文字列補間式で書いてみてください。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-1/Program.cs
> +            Console.WriteLine(wYearMonth.AddOneMonth());//2000年5月と出力
動作チェックをする際は、テスト技法に基づいて境界値などに気を付けて確認してみて下さい。
少なくとも、if文の分岐をすべて網羅するようなテストができると良いです。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-2/Program.cs
> +            foreach (YearMonth ArrayYearMonth in ArrayYearMonths) {
ArrayYearMonthは、1要素の名前としてはおかしいと思います。
命名し直してみてください。
また、コーディング規約に沿った接頭辞を付けてください。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-2/Program.cs
> +        static YearMonth ChooseFirstYearMonth(YearMonth[] vYMArrays) {
引数の名前が、Arraysだと配列が複数あるように感じるので変更してください。
配列だからといって無理にArrayという単語をいれなくても大丈夫です。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-2/Program.cs
> +            return FirstYearMonth;
リファクタリングの余地があります。
21世紀が見つかった時、わざわざbreakしなくてもreturnしてしまえばforeach文を抜けられます。
returnは、1メソッドにつき1つという決まりはないので、処理の流れを見ながら適宜活用してみてください。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-2/Program.cs
> +            }
テキスト4.4にある条件演算子などをつかってリファクタリングしてみてください。
1行で書くことができます。

[追加要望]
ChooseFirstYearMonthメソッドを使わずにLINQで書いてみてください。

2023-01-19 02:38 UTC, k-miyahara-being commented on chapter4/Question4-2/Program.cs
> +                Console.WriteLine(wArrayYearAddMonths_List);
変数宣言は不要です。

2023-01-19 05:42 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Month { get; private set; }
どこからも書き換えられないように、`get`のみでプロパティを定義するように修正しました。

2023-01-19 05:43 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +            if (Month == 12) {
`Month`プロパティ、`Year`プロパティを読み取る際に`this`を付けるようにしました。

2023-01-19 05:45 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +                Month = 1;
新年が始まることを抜けていました。
年を+1しました。

2023-01-19 05:46 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +            //ここを実装する
不要なコメントを削除しました。

2023-01-19 05:47 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +            return StringDay;
変数宣言を削除し、そのまま戻り値に書くようにしました。

2023-01-19 07:02 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
bool型に変えて、21世紀の範囲内ならtrue、それ以外ならfalseとなるようにしました。

2023-01-19 07:06 UTC, ohdaira-being commented on chapter4/Question4-1/Program.cs
> +            Console.WriteLine(wYearMonth.AddOneMonth());//2000年5月と出力
境界値として、2000年12月、2001年1月、2100年12月、2101年1月
同値として、2050年6月
をそれぞれ使うようにしました。

2023-01-19 07:14 UTC, ohdaira-being commented on chapter4/Question4-2/Program.cs
> +        static YearMonth ChooseFirstYearMonth(YearMonth[] vYMArrays) {
引数をvYearMonthsに変更しました。

2023-01-19 08:10 UTC, ohdaira-being commented on chapter4/Question4-2/Program.cs
> +                Console.WriteLine(wArrayYearAddMonths_List);
直接`foreach`文に書き込みました。

2023-01-20 00:58 UTC, ohdaira-being commented on chapter4/Question4-2/Program.cs
> +            foreach (YearMonth ArrayYearMonth in ArrayYearMonths) {
名前が配列を示していました。
wYearMonthに書き直しました。

2023-01-20 01:10 UTC, ohdaira-being commented on chapter4/Question4-2/Program.cs
> +            }
nullチェックとnull合体演算子を使って、一行で書きました。

【追加要望】
ChooseFirstYearMonthメソッドを使わずに、しました。
FirstOrDefaultメソッドを使いました。

2023-01-20 01:20 UTC, ohdaira-being commented on chapter4/Question4-2/Program.cs
> +            return FirstYearMonth;
returnでforeach文を抜けるようにしました。
foreach文でf文の条件に合う要素を返すようにしました。
if文を通る場合、returnで値を返し、通らない場合はnullを返すようにしたことで、変数が減りました。

2023-01-31 10:34 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
今回の場合、Year, Monthは読み取り専用なのでコンストラクタ以降に書き換わることはないため、コンストラクタで21世紀かを判定する処理を書いても問題ありません。
しかし、これらがどこかで書き換わる可能性があるプロパティだった場合、Is21Centuryは常にコンストラクタで決まったものに固定されてしまい、矛盾が生じる場合があります。
Is21Centuryのgetterで判定処理を行うことで、そのときのYear, Monthによって判定できるようになります。
フィールド変数も不要になるので、そちらでの実装も試してみてください。

2023-01-31 10:42 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +            return StringDay;
メソッドをより簡略化することができます。

2023-01-31 10:46 UTC, k-miyahara-being commented on chapter4/Question4-2/Program.cs
> +            }
・追加要望のほうについて
`== true` は省略できます。

2023-02-01 05:16 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
21世紀かを判定する処理をプロパティで実装しました。
Is21Centuryプロパティ内でYearプロパティの値を参照、判定し、boolを返すように実装しました。
フィールド変数とsetterは不要なので、削除しました。

2023-02-01 05:16 UTC, ohdaira-being commented on chapter4/Question4-2/Program.cs
> +            }
省略しました。
bool型は基本的に省略するんですね。

2023-02-02 01:04 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
修正方法はOKです！
が、さらに簡略化できます。1行で書くことができます。
プロパティの型と、if文の条件式はbool値であるということに注目してみてください。

2023-02-02 01:42 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
条件式中の比較演算子`&&`は、bool型を返すので、わざわざif文を書かなくても良かったです。
比較演算子の結果をそのままreturnするように修正しました。

2023-02-02 02:48 UTC, k-miyahara-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
getterのみなので簡略化できます。

2023-02-02 02:55 UTC, ohdaira-being commented on chapter4/Question4-1/YearMonth.cs
> +        public int Is21Century {
簡略化して、書き直しました。

2023-02-02 03:41 UTC, k-miyahara-being approved these changes

2023-02-02 04:01 UTC, merged