5章　章末問題
odaira1119/textC- pull request #5
Opened 2023-01-19 04:54 UTC by ohdaira-being

2023-01-20 10:18 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-01-20 10:18 UTC, k-miyahara-being commented on chapter5/Question5-1/Program.cs
> +                Console.WriteLine("一致していません。");
日本語入力に対応しようとしてくれていますが、「カステラ」「かすてら」と入力しても一致判定になりません。
もう一度テキストを見直して修正してみてください。

2023-01-20 10:18 UTC, k-miyahara-being commented on chapter5/Question5-2/Program.cs
> +            if(int.TryParse(Console.ReadLine(), out int wInputNumber) == false){
`== false`とは別の書き方をしてみてください。

2023-01-20 10:18 UTC, k-miyahara-being commented on chapter5/Question5-3/Program.cs
> +            Console.WriteLine(wInitialText.Count(x => x == (' ')));
余分な括弧があります。
行にカーソルを当てて、電球マークが出ているときは改善できる箇所があることを表しています。
必ずしも提示されたヒントの通りに直す必要はありませんが、自分の書いたコードを見直す際に参考にすると良いです。

2023-01-20 10:18 UTC, k-miyahara-being commented on chapter5/Question5-3/Program.cs
> +            var wStringBuilder = new StringBuilder(200);
StringBuilderのインスタンス生成時に、200文字分のメモリ領域を確保するように初期値を指定していますが、実際に作られる文字列は30字程度です。
想定される文字列に対して必要な領域分を事前に確保しておくことは非常に有効ですが、今回の場合は無駄に確保している感があります。
テキスト通りに書くのではなく、なぜその値を初期値とするのかを考えてみると良いです。

2023-01-20 10:18 UTC, k-miyahara-being commented on chapter5/Question5-4/Program.cs
> +                );
既存の文字列を置き換えていく方法は予想外でした...！
せっかくなので、StringBuilderを使わない他の方法も考えて実装してみてください。
文字列から欲しい部分だけ抽出するイメージです。

2023-01-23 00:20 UTC, ohdaira-being commented on chapter5/Question5-1/Program.cs
> +                Console.WriteLine("一致していません。");
ひらがなとカタカナ、全角と半角を区別しないように、`CompareOptions.IgnoreKanaType | CompareOptions.IgnoreWidth`を条件式に追加しました。

2023-01-23 00:22 UTC, ohdaira-being commented on chapter5/Question5-2/Program.cs
> +            if(int.TryParse(Console.ReadLine(), out int wInputNumber) == false){
`==false`を削除し、文頭に`!`を付けました。

2023-01-23 00:23 UTC, ohdaira-being commented on chapter5/Question5-3/Program.cs
> +            Console.WriteLine(wInitialText.Count(x => x == (' ')));
電球マークの提案を使って、ラムダ式内の括弧を削除しました。

2023-01-23 00:27 UTC, ohdaira-being commented on chapter5/Question5-3/Program.cs
> +            var wStringBuilder = new StringBuilder(200);
承知しました。
無駄に確保しすぎないように、していきます。
今回は、余裕をもって50文字分の領域を確保するように修正しましrた。

2023-01-23 00:48 UTC, ohdaira-being commented on chapter5/Question5-4/Program.cs
> +                );
`StringBuilder`を使わずに、`Split`と`StringSplitOptions.RemoveEmptyEntries`を使って実装し直しました。

2023-01-31 10:54 UTC, k-miyahara-being commented on chapter5/Question5-1/Program.cs
> +                Console.WriteLine("一致していません。");
修正はOKです。
せっかくなので、`|` と `||` の違いについてまだ調べたことがなければ調べてみてください。
どちらも、"または"を表す演算子ですが、実は違いがあります。
参考サイト↓
https://www.fenet.jp/dotnet/column/language/6125/

2023-01-31 10:58 UTC, k-miyahara-being approved these changes

2023-02-01 05:43 UTC, merged