6章　章末問題
odaira1119/textC- pull request #6
Opened 2023-01-22 23:57 UTC by ohdaira-being

2023-02-07 02:57 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-1/Program.cs
> +            var numbers = new int[] { 5, 10, 17, 9, 3, 21, 10, 40, 21, 3, 35 };
コーディング規約に沿った接頭辞を付けてください。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-1/Program.cs
> +            Console.WriteLine(numbers.Take(numbers.Length - 1).LastOrDefault());
問題の意図としては、「最後から2つ目」ではなく「末尾の2つ」を取り出すということかと思います。（3と35が出力されることが期待）

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-1/Program.cs
> +            Console.WriteLine(String.Join(" ", numbers.Select(x => x.ToString())));
[要望]
数字が文字列であることを示すために、4桁の0埋め（ゼロパディング）で出力してみてください。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-2/Book.cs
> +        public int Pages{ get;set;}
クラスと同様にプロパティにも説明を付けてください。

また、空白が揃っていないので揃えてください。
プロパティを書く際の小技の紹介です。
`prop`と入力してtabキーを2回押すと、自動でプロパティのテンプレートを入力してくれます。

他にも、for文なら`for`と打ってtabキーを2回、foreach文なら`fore`まで打ってtabキー2回とするとテンプレートを自動入力してくれます。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +            };
[要望]
初期化子ではなく、コンストラクタで各プロパティの値を設定できるように修正してみてください。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +                $"ページ数は、{wBooks.FirstOrDefault(x => x.Title == "ワンダフル・C#ライフ").Pages}ページです。"
[要望]
対応する書籍が見つからなった時に、「一致する書籍は見つかりませんでした。」と表示するコードを書いてみてください。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +                $"{Math.Ceiling(wBooks.Where(x => x.Title.Contains("C#")).Average(y => y.Pages))}ページです。"
問2、3、7では同じ書籍を探しているので、複数箇所で同じ処理を書くよりも変数に格納して使いまわすほうがコストが少ない、かつ可読性の向上が期待できます。
「タイトルに「C#」が含まれている書籍」 のリストを作っておくと使いやすいです。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +                );
[要望]
6000円以上の本を探すコードを書いてください。
見つからないときのメッセージが出力されるようにしてください。

2023-02-07 02:57 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +                $"{wBooks.Where(x => x.Price < 4000).Max(y => y.Pages)}ページです。"
明確な決まりはないですが、ラムダ式でyを使うのは、ラムダ式の中にさらにラムダ式がある場合です。
今回の場合、xとyは同じ粒度で使われているのでどちらもxで問題ないです。
他の箇所も同様です。

2023-02-07 05:52 UTC, ohdaira-being commented on chapter6/Question6-1/Program.cs
> +            var numbers = new int[] { 5, 10, 17, 9, 3, 21, 10, 40, 21, 3, 35 };
wNumbersに修正しました。

2023-02-07 06:16 UTC, ohdaira-being commented on chapter6/Question6-1/Program.cs
> +            Console.WriteLine(numbers.Take(numbers.Length - 1).LastOrDefault());
foreach文を使って、末尾から二つの要素を取り出すように修正しました。

2023-02-07 06:25 UTC, ohdaira-being commented on chapter6/Question6-1/Program.cs
> +            Console.WriteLine(String.Join(" ", numbers.Select(x => x.ToString())));
PadLeft()で実装しました。

2023-02-07 06:28 UTC, ohdaira-being commented on chapter6/Question6-2/Book.cs
> +        public int Pages{ get;set;}
ありがとうございます。
スピードを上げるためにも積極的に使っていきます。

プロパティに説明を追加しました。

2023-02-07 06:41 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +            };
コンストラクタを使うように修正しました。

2023-02-07 06:48 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +                $"ページ数は、{wBooks.FirstOrDefault(x => x.Title == "ワンダフル・C#ライフ").Pages}ページです。"
条件分岐で書きました。

2023-02-07 06:54 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +                $"{Math.Ceiling(wBooks.Where(x => x.Title.Contains("C#")).Average(y => y.Pages))}ページです。"
書き直してみたところ、コードが少しスッキリしました。

2023-02-07 07:00 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +                );
条件分岐で書きました。

2023-02-07 07:03 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +                $"{wBooks.Where(x => x.Price < 4000).Max(y => y.Pages)}ページです。"
xyzと使っていくのは、ラムダ式の中の話なんですね。
勘違いしていました。。。

ラムダ式中にラムダ式を書いている箇所がなかったので、すべてxで書き直しました。

2023-02-07 10:02 UTC, k-miyahara-being commented on chapter6/Question6-1/Program.cs
> +            Console.WriteLine(String.Join(" ", numbers.Select(x => x.ToString())));
特別なメソッドを使わずとも、ToStringに引数を与えればOKです。
参考： テキストp.178

2023-02-07 10:04 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +            };
OKです。
インスタンス生成時にTitleの後ろに空白を入れているのは意味がありますか？
不要であれば消してください。

2023-02-07 10:09 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +                $"{Math.Ceiling(wBooks.Where(x => x.Title.Contains("C#")).Average(y => y.Pages))}ページです。"
OKです。
ただし、ローカル変数を宣言するときは必要になったタイミングで宣言するようにしてください。
問1の前で宣言していると、問1でも使うのかな?となります。

2023-02-07 10:12 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +                );
すみません、6000円以上の本で最初に見つかった書籍を取り出してもらう想定でした。
再度修正してみてください。

2023-02-08 02:31 UTC, ohdaira-being commented on chapter6/Question6-1/Program.cs
> +            Console.WriteLine(String.Join(" ", numbers.Select(x => x.ToString())));
引数で渡してあげるだけで、できました。
読んだはずなのに忘れていました…。

2023-02-08 02:35 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +            };
列挙する際、段落を合わせるようにすると、読みやすく、誤字などのミスを見つけやすいとリーダブルコードに書いていたので、空白で合わせました。
空白で合わせていた方が読みやすいかな、と思ったのですが、消した方がいいですか？

コメントアウトしていたコードを削除しました。

2023-02-08 02:38 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +                $"{Math.Ceiling(wBooks.Where(x => x.Title.Contains("C#")).Average(y => y.Pages))}ページです。"
宣言は必要になったタイミングで行う、ために宣言する箇所を移動しました。

2023-02-08 03:31 UTC, ohdaira-being commented on chapter6/Question6-2/Program.cs
> +                );
書き直しました。

不要になったコードは削除しました。

2023-02-08 08:16 UTC, k-miyahara-being commented on chapter6/Question6-2/Program.cs
> +            };
なるほど、わかりました。
ただ、こちらの環境で見た感じではカンマで揃っている風には見えませんでした。
また、一番長い値にそろえているようですが、今後さらに長い値が追加された場合、またそろえ直すのは苦労すると思います。
プログラム的には問題ないですが、余計な空白は入れないことが無難かなと思います。
書籍の内容を実践しているのはとてもGoodです！

2023-02-08 08:19 UTC, k-miyahara-being approved these changes
OKです。

2023-02-09 05:11 UTC, merged