7章　章末問題
odaira1119/textC- pull request #7
Opened 2023-01-24 02:42 UTC by ohdaira-being

2023-02-07 04:52 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-1/Program.cs
> +            string wText = "Cozy lummox gives smart squid who asks for job pen".Replace(" ", "").ToUpper();
すべて大文字にしたあとの文字列を変数にしておくのは良いですが、
"Cozy ... pen" という文字列はテキストが用意した定数です。
定数は定数として定義しておき、直接使用することは避けたほうがよいです。
理由は、将来的に別の場所で"Cozy ... pen" という文字列を大文字小文字を区別せずに使いたいときにwTextだと使えないからです。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-1/Program.cs
> +            }
[要望]
ToDictionaryメソッドを使った方法も実装してみてください。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public int Count => wDict.Count();
プロパティの説明を記述してください。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        private Dictionary<string, string> wDict = new Dictionary<string, string>();
接頭辞がコーディング規約に沿っていないです。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public bool Remove(string vRemoveText) {
他のメソッドと同様に説明を記述してください。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        /// <param name="vJapanese">ディクショナリwDictに追加する値</param>
具体的に何を表す変数なのかが書かれていると良いです。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        }
式を簡略化できます。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        }
ここも簡略化できます。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        /// 日本語の位置を引数に与え、それが含まれる要素(Key, Value)を全て取り出す
位置 → 一部 が正しいと思います。
テキストの誤字ですが、メソッドの意味を考えて気づけると良いですね

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +            foreach (var wItem in wDict) {
明示的な型にしてください。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public IEnumerable<KeyValuePair<string, string>> FindKeyAllAtNum(int vKeyCharNum) {
3文字に限らず指定した文字数の要素を取り出せるメソッドにしたのはGoodです！
メソッド名、引数名、ローカル変数名が少しわかりづらいので、もう少しシンプルにしてみると良いかもしれません。

2023-02-07 04:52 UTC, k-miyahara-being commented on chapter7/Question7-2/Program.cs
> +            Abbreviations wSampleDict = new Abbreviations();
変数名を目的に沿ったものにしてください。

2023-02-07 07:19 UTC, ohdaira-being commented on chapter7/Question7-1/Program.cs
> +            string wText = "Cozy lummox gives smart squid who asks for job pen".Replace(" ", "").ToUpper();
そうですね、与えられた定数は、そのまま定義しておくべきでした。
与えられたものは、そのまま定義して、使う時にそれぞれ変更を加えるように修正しました。

2023-02-07 09:00 UTC, ohdaira-being commented on chapter7/Question7-1/Program.cs
> +            }
重複した要素を削除するDistinct()と違って、重複した要素を保持し続けるGroupBy()を使って書きました。

2023-02-07 09:03 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public int Count => wDict.Count();
追加しました。

2023-02-07 09:04 UTC, odaira1119 commented on chapter7/Question7-2/Abbreviations.cs
> +        private Dictionary<string, string> wDict = new Dictionary<string, string>();
wを削除しました。

2023-02-07 09:07 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public bool Remove(string vRemoveText) {
追加しました。

2023-02-07 09:07 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        }
簡略化しました。

2023-02-07 09:09 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        /// 日本語の位置を引数に与え、それが含まれる要素(Key, Value)を全て取り出す
修正しました。
次は、気づけるように一つ一つしっかり読み進めていこうと思います。

2023-02-07 09:10 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +            foreach (var wItem in wDict) {
varをKeyValuePair<string, string>にし、明示的にしました。

2023-02-07 09:17 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public IEnumerable<KeyValuePair<string, string>> FindKeyAllAtNum(int vKeyCharNum) {
メソッド名：FindDictAtCharNums
引数名：vCharNums
ローカル変数名：wDict
にそれぞれ変更しました。

2023-02-07 09:19 UTC, ohdaira-being commented on chapter7/Question7-2/Program.cs
> +            Abbreviations wSampleDict = new Abbreviations();
wAbbreviationsDictに変更しました。

2023-02-08 08:28 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public bool Remove(string vRemoveText) {
式を簡略化できます。

2023-02-08 08:29 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        }
修正されていないので再度確認してください。

2023-02-08 09:13 UTC, k-miyahara-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public IEnumerable<KeyValuePair<string, string>> FindKeyAllAtNum(int vKeyCharNum) {
ローカル変数名について、Dictはディクショナリです。
foreachで回している各要素はディクショナリではないので、他の箇所同様Itemとかが適しているかと思います。

2023-02-09 05:16 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public bool Remove(string vRemoveText) {
Removeメソッド、Addメソッド、ToAddreviationsメソッドを簡略化しました。

2023-02-09 05:17 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        }
簡略化しました。

2023-02-09 05:18 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        public IEnumerable<KeyValuePair<string, string>> FindKeyAllAtNum(int vKeyCharNum) {
Dictは、おかしかったです。
wItemに変更しました。

2023-02-10 07:58 UTC, ohdaira-being commented on chapter7/Question7-2/Abbreviations.cs
> +        /// <param name="vJapanese">ディクショナリwDictに追加する値</param>
修正しました

2023-02-13 00:53 UTC, k-miyahara-being approved these changes
OKです。

2023-02-13 00:55 UTC, merged