8章　章末問題
odaira1119/textC- pull request #8
Opened 2023-01-25 02:24 UTC by ohdaira-being

2023-02-07 05:44 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-07 05:44 UTC, k-miyahara-being commented on chapter8/Question8-1/Program.cs
> +            Console.WriteLine(wNow.ToString($"ggyy年{wNow.Month,2}月{wNow.Day,2}日（{wDayOfWeek}）", wCulture));
曜日の取得は実はもっと簡単な方法があります。
テキストp.208をもう一度隅々まで読んでみてください。

2023-02-07 05:44 UTC, k-miyahara-being commented on chapter8/Question8-2/Program.cs
> +        public static DateTime NextWeekDay(DateTime vDate, DayOfWeek vDayOfWeek) {
命名についてですが、NextWeekDayだと「次の平日」を取得するメソッドに誤解される可能性があります。
非常に細かいですが別の名前を考えてみてください。

2023-02-07 05:44 UTC, k-miyahara-being commented on chapter8/Question8-2/Program.cs
> +            int wDays = ((int)DayOfWeek.Saturday - (int)vDate.DayOfWeek) + (int)vDayOfWeek + 1;
式を見直してみてください。起点は不要になります。
参考：テキストp.215~216

2023-02-07 05:44 UTC, k-miyahara-being commented on chapter8/Question8-3/TimeWatch.cs
> +        }
式を簡略化できます。

2023-02-07 05:44 UTC, k-miyahara-being commented on chapter8/Question8-3/TimeWatch.cs
> +        private DateTime wStart;
接頭辞がコーディング規約に沿っていません。

2023-02-07 05:44 UTC, k-miyahara-being commented on chapter8/Question8-3/Program.cs
> +    class Program : TimeWatch {
TimeWatchクラスを継承しているのは何か意図がありますか？

2023-02-08 01:15 UTC, ohdaira-being commented on chapter8/Question8-1/Program.cs
> +            Console.WriteLine(wNow.ToString($"ggyy年{wNow.Month,2}月{wNow.Day,2}日（{wDayOfWeek}）", wCulture));
簡易的に書き直しました。

2023-02-08 01:24 UTC, ohdaira-being commented on chapter8/Question8-2/Program.cs
> +        public static DateTime NextWeekDay(DateTime vDate, DayOfWeek vDayOfWeek) {
NextDayOfWeekに変更しました。

2023-02-08 01:50 UTC, ohdaira-being commented on chapter8/Question8-2/Program.cs
> +            int wDays = ((int)DayOfWeek.Saturday - (int)vDate.DayOfWeek) + (int)vDayOfWeek + 1;
`(int)DayOfWeek.Saturday`と1をまとめて、`7（1週間の日数）-今日の曜日`で次の日曜日を求め、そこに指定曜日を足すようにしました。

2023-02-08 01:53 UTC, ohdaira-being commented on chapter8/Question8-3/TimeWatch.cs
> +        }
メソッドにも式本体を使えるんですね。
簡略化しました。

2023-02-08 01:54 UTC, ohdaira-being commented on chapter8/Question8-3/TimeWatch.cs
> +        private DateTime wStart;
FStartedTimeに命名し直しました。

2023-02-08 01:55 UTC, ohdaira-being commented on chapter8/Question8-3/Program.cs
> +    class Program : TimeWatch {
何も意図はありません。
削除しました。

2023-02-08 10:00 UTC, k-miyahara-being commented on chapter8/Question8-2/Program.cs
> +            int wDays = ((int)DayOfWeek.Saturday - (int)vDate.DayOfWeek) + (int)vDayOfWeek + 1;
OKです。
変数をなくす ＆ 式を簡略化できます。

2023-02-08 10:03 UTC, k-miyahara-being commented on chapter8/Question8-3/TimeWatch.cs
> +        private DateTime wStart;
thisは無くしておきましょう。

2023-02-09 05:39 UTC, ohdaira-being commented on chapter8/Question8-2/Program.cs
> +            int wDays = ((int)DayOfWeek.Saturday - (int)vDate.DayOfWeek) + (int)vDayOfWeek + 1;
変数をなくし、式を簡略化しました。

2023-02-09 05:40 UTC, ohdaira-being commented on chapter8/Question8-3/TimeWatch.cs
> +        private DateTime wStart;
不要なthisを削除しました。

2023-02-09 07:00 UTC, k-miyahara-being approved these changes
OKです。

2023-02-10 08:00 UTC, merged