9章　章末問題
odaira1119/textC- pull request #9
Opened 2023-02-02 04:02 UTC by ohdaira-being

2023-02-07 06:44 UTC, k-miyahara-being requested changes
修正をお願いします。

2023-02-07 06:44 UTC, k-miyahara-being commented on chapter9/Question9-1/CountClass.cs
> +            var wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter9\CountClass.txt";
修正不要です。
問題にはC#のソースファイルとあるので、テキストファイルではなくcsファイルを指定するのが正しいです。

2023-02-07 06:44 UTC, k-miyahara-being commented on chapter9/Question9-1/CountClass.cs
> +            int wCount = 0;
この変数のスコープをより小さくできます。

2023-02-07 06:44 UTC, k-miyahara-being commented on chapter9/Question9-1/CountClass.cs
> +                            wCount++;
if文の中身が1行しかない場合は、{}で囲まずに1行で書いてしまっても良いです。

2023-02-07 06:44 UTC, k-miyahara-being commented on chapter9/Question9-2/Program.cs
> +            var wOutputFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter9\Copy.txt";
ローカルの絶対パスでは他のPCで実行したときファイルが見つかりません。
相対パスを使用してください。
また、明示的な型を使用してください。

2023-02-07 06:44 UTC, k-miyahara-being commented on chapter9/Question9-3/Program.cs
> +    class Program {
全般的なアドバイスです。
メソッド内でも、行う処理のかたまりを意識して適宜空行を入れると読みやすいです。
切れ目があることで、一旦ここまで読めばいいんだ、ということが視覚的に伝わります。
文章を書く時に段落を入れるのと同じイメージです。
かたまりごとにコメントを入れておくのも良いですね。

2023-02-07 06:44 UTC, k-miyahara-being commented on chapter9/Question9-5/Program.cs
> +                }
指定したディレクトリ内でサブディレクトリ分も含めてすべてのファイルを取得する方法があります。
参考：https://dobon.net/vb/dotnet/file/getfiles.html

2023-02-08 06:03 UTC, ohdaira-being commented on chapter9/Question9-1/CountClass.cs
> +            var wFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter9\CountClass.txt";
テキストファイルで申し訳ありません。
以降、気を付けます。

2023-02-08 06:05 UTC, ohdaira-being commented on chapter9/Question9-1/CountClass.cs
> +            int wCount = 0;
宣言する箇所を移動して、スコープを狭くしました。

2023-02-08 06:06 UTC, ohdaira-being commented on chapter9/Question9-1/CountClass.cs
> +                            wCount++;
{}を削除し、一行で書き直しました。

2023-02-08 06:08 UTC, ohdaira-being commented on chapter9/Question9-2/Program.cs
> +            var wOutputFilePath = @"C:\Users\ohdaira\Desktop\C#成果物\idiom\chapter9\Copy.txt";
相対パスで書き直し、型を明示的に宣言しました。

2023-02-08 06:13 UTC, ohdaira-being commented on chapter9/Question9-3/Program.cs
> +    class Program {
アドバイス、ありがとうございます。
処理のかたまり間に空行を入れたり、そのかたまりにコメントを入れたり、
工夫してみます。

2023-02-08 06:42 UTC, ohdaira-being commented on chapter9/Question9-5/Program.cs
> +                }
GetFilesの引数にSearchOption.AllDirectoriesをするだけで取得できました。
非常に短いコードになりました。

2023-02-09 01:39 UTC, k-miyahara-being approved these changes
OKです。

2023-02-09 05:43 UTC, merged